// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.1
// source: config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValueType 配置值类型
type ValueType int32

const (
	ValueType_VALUE_TYPE_UNSPECIFIED ValueType = 0
	ValueType_VALUE_TYPE_STRING      ValueType = 1
	ValueType_VALUE_TYPE_INT         ValueType = 2
	ValueType_VALUE_TYPE_FLOAT       ValueType = 3
	ValueType_VALUE_TYPE_BOOL        ValueType = 4
	ValueType_VALUE_TYPE_REF         ValueType = 5
	ValueType_VALUE_TYPE_OBJECT      ValueType = 6
	ValueType_VALUE_TYPE_ARRAY       ValueType = 7
	ValueType_VALUE_TYPE_ENCRYPTED   ValueType = 8
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "VALUE_TYPE_UNSPECIFIED",
		1: "VALUE_TYPE_STRING",
		2: "VALUE_TYPE_INT",
		3: "VALUE_TYPE_FLOAT",
		4: "VALUE_TYPE_BOOL",
		5: "VALUE_TYPE_REF",
		6: "VALUE_TYPE_OBJECT",
		7: "VALUE_TYPE_ARRAY",
		8: "VALUE_TYPE_ENCRYPTED",
	}
	ValueType_value = map[string]int32{
		"VALUE_TYPE_UNSPECIFIED": 0,
		"VALUE_TYPE_STRING":      1,
		"VALUE_TYPE_INT":         2,
		"VALUE_TYPE_FLOAT":       3,
		"VALUE_TYPE_BOOL":        4,
		"VALUE_TYPE_REF":         5,
		"VALUE_TYPE_OBJECT":      6,
		"VALUE_TYPE_ARRAY":       7,
		"VALUE_TYPE_ENCRYPTED":   8,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

// ConfigValue 配置值
type ConfigValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                                      // 配置值
	Type          ValueType              `protobuf:"varint,2,opt,name=type,proto3,enum=xiaozhizhang.config.v1.ValueType" json:"type,omitempty"` // 配置类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValue) Reset() {
	*x = ConfigValue{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValue) ProtoMessage() {}

func (x *ConfigValue) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValue.ProtoReflect.Descriptor instead.
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigValue) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_VALUE_TYPE_UNSPECIFIED
}

// CreateConfigRequest 创建配置请求
type CreateConfigRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                                                                     // 配置键（带环境后缀，如 app.cert.dev）
	Value         map[string]*ConfigValue `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // 配置值，key为属性名
	Metadata      map[string]string       `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	Description   string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                                                     // 配置描述
	ChangeNote    string                  `protobuf:"bytes,5,opt,name=change_note,json=changeNote,proto3" json:"change_note,omitempty"`                                                     // 变更说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConfigRequest) Reset() {
	*x = CreateConfigRequest{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigRequest) ProtoMessage() {}

func (x *CreateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateConfigRequest) GetValue() map[string]*ConfigValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CreateConfigRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateConfigRequest) GetChangeNote() string {
	if x != nil {
		return x.ChangeNote
	}
	return ""
}

// UpdateConfigRequest 更新配置请求
type UpdateConfigRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                                                                     // 配置键（带环境后缀，如 app.cert.dev）
	Value         map[string]*ConfigValue `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // 配置值，key为属性名
	Metadata      map[string]string       `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	Description   string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                                                     // 配置描述
	ChangeNote    string                  `protobuf:"bytes,5,opt,name=change_note,json=changeNote,proto3" json:"change_note,omitempty"`                                                     // 变更说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateConfigRequest) GetValue() map[string]*ConfigValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateConfigRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateConfigRequest) GetChangeNote() string {
	if x != nil {
		return x.ChangeNote
	}
	return ""
}

// DeleteConfigRequest 删除配置请求
type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 配置键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteConfigResponse 删除配置响应
type DeleteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetConfigForAdminRequest 获取配置请求（管理端）
type GetConfigForAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 配置键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigForAdminRequest) Reset() {
	*x = GetConfigForAdminRequest{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigForAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigForAdminRequest) ProtoMessage() {}

func (x *GetConfigForAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigForAdminRequest.ProtoReflect.Descriptor instead.
func (*GetConfigForAdminRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *GetConfigForAdminRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// ListConfigsForAdminRequest 列表查询请求（管理端）
type ListConfigsForAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                         // 配置键（支持模糊查询）
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`         // 环境
	PageNum       int32                  `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"` // 页码
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                      // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsForAdminRequest) Reset() {
	*x = ListConfigsForAdminRequest{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsForAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsForAdminRequest) ProtoMessage() {}

func (x *ListConfigsForAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsForAdminRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsForAdminRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *ListConfigsForAdminRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListConfigsForAdminRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ListConfigsForAdminRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListConfigsForAdminRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ListConfigsForAdminResponse 列表查询响应（管理端）
type ListConfigsForAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []*ConfigResponse      `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"` // 配置列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`    // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsForAdminResponse) Reset() {
	*x = ListConfigsForAdminResponse{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsForAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsForAdminResponse) ProtoMessage() {}

func (x *ListConfigsForAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsForAdminResponse.ProtoReflect.Descriptor instead.
func (*ListConfigsForAdminResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *ListConfigsForAdminResponse) GetContent() []*ConfigResponse {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ListConfigsForAdminResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdateConfigStatusRequest 更新配置状态请求
type UpdateConfigStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`       // 配置键
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigStatusRequest) Reset() {
	*x = UpdateConfigStatusRequest{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigStatusRequest) ProtoMessage() {}

func (x *UpdateConfigStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigStatusRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateConfigStatusRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateConfigStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ConfigResponse 配置响应
type ConfigResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                      // ID
	Key           string                  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                                                                     // 配置键（带环境后缀，如 app.cert.dev）
	Value         map[string]*ConfigValue `protobuf:"bytes,3,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // 配置值，key为属性名
	Version       int64                   `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                                                                            // 版本号
	Metadata      map[string]string       `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	Description   string                  `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                                                                     // 配置描述
	CreatedAt     string                  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                        // 创建时间
	UpdatedAt     string                  `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                        // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigResponse) GetValue() map[string]*ConfigValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConfigResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ConfigResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// GetConfigRequest 获取配置请求（查询端）
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 配置键（可以是带环境后缀的完整key，如 app.cert.dev；也可以是不带环境的key，配合 env 参数使用）
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"` // 环境（如果 key 已带环境后缀，该参数可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetConfigRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// GetConfigResponse 获取配置响应（查询端）
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonStr       string                 `protobuf:"bytes,1,opt,name=json_str,json=jsonStr,proto3" json:"json_str,omitempty"` // JSON字符串格式的配置值（纯对象，可直接反序列化到业务结构体）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfigResponse) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

// BatchGetConfigsRequest 批量获取配置请求
type BatchGetConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"` // 配置键列表（可以是带环境后缀的完整key，也可以是不带环境的key，配合 env 参数使用）
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`   // 环境（如果 keys 中已带环境后缀，该参数可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetConfigsRequest) Reset() {
	*x = BatchGetConfigsRequest{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetConfigsRequest) ProtoMessage() {}

func (x *BatchGetConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetConfigsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetConfigsRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetConfigsRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *BatchGetConfigsRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// BatchGetConfigsResponse 批量获取配置响应
type BatchGetConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]string      `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配置映射，key为配置键，value为JSON字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetConfigsResponse) Reset() {
	*x = BatchGetConfigsResponse{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetConfigsResponse) ProtoMessage() {}

func (x *BatchGetConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetConfigsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetConfigsResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetConfigsResponse) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

// GetConfigsByPrefixRequest 按前缀获取配置请求
type GetConfigsByPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // 配置键前缀
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`       // 环境（如 dev, prod, test）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigsByPrefixRequest) Reset() {
	*x = GetConfigsByPrefixRequest{}
	mi := &file_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigsByPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigsByPrefixRequest) ProtoMessage() {}

func (x *GetConfigsByPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigsByPrefixRequest.ProtoReflect.Descriptor instead.
func (*GetConfigsByPrefixRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{14}
}

func (x *GetConfigsByPrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GetConfigsByPrefixRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// GetConfigsByPrefixResponse 按前缀获取配置响应
type GetConfigsByPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]string      `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配置映射，key为完整配置键（含环境后缀），value为JSON字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigsByPrefixResponse) Reset() {
	*x = GetConfigsByPrefixResponse{}
	mi := &file_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigsByPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigsByPrefixResponse) ProtoMessage() {}

func (x *GetConfigsByPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigsByPrefixResponse.ProtoReflect.Descriptor instead.
func (*GetConfigsByPrefixResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{15}
}

func (x *GetConfigsByPrefixResponse) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x16xiaozhizhang.config.v1\"Z\n" +
	"\vConfigValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.xiaozhizhang.config.v1.ValueTypeR\x04type\"\xab\x03\n" +
	"\x13CreateConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12L\n" +
	"\x05value\x18\x02 \x03(\v26.xiaozhizhang.config.v1.CreateConfigRequest.ValueEntryR\x05value\x12U\n" +
	"\bmetadata\x18\x03 \x03(\v29.xiaozhizhang.config.v1.CreateConfigRequest.MetadataEntryR\bmetadata\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vchange_note\x18\x05 \x01(\tR\n" +
	"changeNote\x1a]\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.xiaozhizhang.config.v1.ConfigValueR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x03\n" +
	"\x13UpdateConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12L\n" +
	"\x05value\x18\x02 \x03(\v26.xiaozhizhang.config.v1.UpdateConfigRequest.ValueEntryR\x05value\x12U\n" +
	"\bmetadata\x18\x03 \x03(\v29.xiaozhizhang.config.v1.UpdateConfigRequest.MetadataEntryR\bmetadata\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vchange_note\x18\x05 \x01(\tR\n" +
	"changeNote\x1a]\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.xiaozhizhang.config.v1.ConfigValueR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x13DeleteConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"J\n" +
	"\x14DeleteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x18GetConfigForAdminRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x7f\n" +
	"\x1aListConfigsForAdminRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12\x19\n" +
	"\bpage_num\x18\x03 \x01(\x05R\apageNum\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"u\n" +
	"\x1bListConfigsForAdminResponse\x12@\n" +
	"\acontent\x18\x01 \x03(\v2&.xiaozhizhang.config.v1.ConfigResponseR\acontent\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"E\n" +
	"\x19UpdateConfigStatusRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xe3\x03\n" +
	"\x0eConfigResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12G\n" +
	"\x05value\x18\x03 \x03(\v21.xiaozhizhang.config.v1.ConfigResponse.ValueEntryR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12P\n" +
	"\bmetadata\x18\x05 \x03(\v24.xiaozhizhang.config.v1.ConfigResponse.MetadataEntryR\bmetadata\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x1a]\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.xiaozhizhang.config.v1.ConfigValueR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x10GetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\".\n" +
	"\x11GetConfigResponse\x12\x19\n" +
	"\bjson_str\x18\x01 \x01(\tR\ajsonStr\">\n" +
	"\x16BatchGetConfigsRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\"\xad\x01\n" +
	"\x17BatchGetConfigsResponse\x12V\n" +
	"\aconfigs\x18\x01 \x03(\v2<.xiaozhizhang.config.v1.BatchGetConfigsResponse.ConfigsEntryR\aconfigs\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x19GetConfigsByPrefixRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\"\xb3\x01\n" +
	"\x1aGetConfigsByPrefixResponse\x12Y\n" +
	"\aconfigs\x18\x01 \x03(\v2?.xiaozhizhang.config.v1.GetConfigsByPrefixResponse.ConfigsEntryR\aconfigs\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd8\x01\n" +
	"\tValueType\x12\x1a\n" +
	"\x16VALUE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VALUE_TYPE_STRING\x10\x01\x12\x12\n" +
	"\x0eVALUE_TYPE_INT\x10\x02\x12\x14\n" +
	"\x10VALUE_TYPE_FLOAT\x10\x03\x12\x13\n" +
	"\x0fVALUE_TYPE_BOOL\x10\x04\x12\x12\n" +
	"\x0eVALUE_TYPE_REF\x10\x05\x12\x15\n" +
	"\x11VALUE_TYPE_OBJECT\x10\x06\x12\x14\n" +
	"\x10VALUE_TYPE_ARRAY\x10\a\x12\x18\n" +
	"\x14VALUE_TYPE_ENCRYPTED\x10\b2\xf7\a\n" +
	"\rConfigService\x12c\n" +
	"\fCreateConfig\x12+.xiaozhizhang.config.v1.CreateConfigRequest\x1a&.xiaozhizhang.config.v1.ConfigResponse\x12c\n" +
	"\fUpdateConfig\x12+.xiaozhizhang.config.v1.UpdateConfigRequest\x1a&.xiaozhizhang.config.v1.ConfigResponse\x12i\n" +
	"\fDeleteConfig\x12+.xiaozhizhang.config.v1.DeleteConfigRequest\x1a,.xiaozhizhang.config.v1.DeleteConfigResponse\x12m\n" +
	"\x11GetConfigForAdmin\x120.xiaozhizhang.config.v1.GetConfigForAdminRequest\x1a&.xiaozhizhang.config.v1.ConfigResponse\x12~\n" +
	"\x13ListConfigsForAdmin\x122.xiaozhizhang.config.v1.ListConfigsForAdminRequest\x1a3.xiaozhizhang.config.v1.ListConfigsForAdminResponse\x12o\n" +
	"\x12UpdateConfigStatus\x121.xiaozhizhang.config.v1.UpdateConfigStatusRequest\x1a&.xiaozhizhang.config.v1.ConfigResponse\x12`\n" +
	"\tGetConfig\x12(.xiaozhizhang.config.v1.GetConfigRequest\x1a).xiaozhizhang.config.v1.GetConfigResponse\x12r\n" +
	"\x0fBatchGetConfigs\x12..xiaozhizhang.config.v1.BatchGetConfigsRequest\x1a/.xiaozhizhang.config.v1.BatchGetConfigsResponse\x12{\n" +
	"\x12GetConfigsByPrefix\x121.xiaozhizhang.config.v1.GetConfigsByPrefixRequest\x1a2.xiaozhizhang.config.v1.GetConfigsByPrefixResponseB,Z*xiaozhizhang/system/config/api/proto;protob\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_config_proto_goTypes = []any{
	(ValueType)(0),                      // 0: xiaozhizhang.config.v1.ValueType
	(*ConfigValue)(nil),                 // 1: xiaozhizhang.config.v1.ConfigValue
	(*CreateConfigRequest)(nil),         // 2: xiaozhizhang.config.v1.CreateConfigRequest
	(*UpdateConfigRequest)(nil),         // 3: xiaozhizhang.config.v1.UpdateConfigRequest
	(*DeleteConfigRequest)(nil),         // 4: xiaozhizhang.config.v1.DeleteConfigRequest
	(*DeleteConfigResponse)(nil),        // 5: xiaozhizhang.config.v1.DeleteConfigResponse
	(*GetConfigForAdminRequest)(nil),    // 6: xiaozhizhang.config.v1.GetConfigForAdminRequest
	(*ListConfigsForAdminRequest)(nil),  // 7: xiaozhizhang.config.v1.ListConfigsForAdminRequest
	(*ListConfigsForAdminResponse)(nil), // 8: xiaozhizhang.config.v1.ListConfigsForAdminResponse
	(*UpdateConfigStatusRequest)(nil),   // 9: xiaozhizhang.config.v1.UpdateConfigStatusRequest
	(*ConfigResponse)(nil),              // 10: xiaozhizhang.config.v1.ConfigResponse
	(*GetConfigRequest)(nil),            // 11: xiaozhizhang.config.v1.GetConfigRequest
	(*GetConfigResponse)(nil),           // 12: xiaozhizhang.config.v1.GetConfigResponse
	(*BatchGetConfigsRequest)(nil),      // 13: xiaozhizhang.config.v1.BatchGetConfigsRequest
	(*BatchGetConfigsResponse)(nil),     // 14: xiaozhizhang.config.v1.BatchGetConfigsResponse
	(*GetConfigsByPrefixRequest)(nil),   // 15: xiaozhizhang.config.v1.GetConfigsByPrefixRequest
	(*GetConfigsByPrefixResponse)(nil),  // 16: xiaozhizhang.config.v1.GetConfigsByPrefixResponse
	nil,                                 // 17: xiaozhizhang.config.v1.CreateConfigRequest.ValueEntry
	nil,                                 // 18: xiaozhizhang.config.v1.CreateConfigRequest.MetadataEntry
	nil,                                 // 19: xiaozhizhang.config.v1.UpdateConfigRequest.ValueEntry
	nil,                                 // 20: xiaozhizhang.config.v1.UpdateConfigRequest.MetadataEntry
	nil,                                 // 21: xiaozhizhang.config.v1.ConfigResponse.ValueEntry
	nil,                                 // 22: xiaozhizhang.config.v1.ConfigResponse.MetadataEntry
	nil,                                 // 23: xiaozhizhang.config.v1.BatchGetConfigsResponse.ConfigsEntry
	nil,                                 // 24: xiaozhizhang.config.v1.GetConfigsByPrefixResponse.ConfigsEntry
}
var file_config_proto_depIdxs = []int32{
	0,  // 0: xiaozhizhang.config.v1.ConfigValue.type:type_name -> xiaozhizhang.config.v1.ValueType
	17, // 1: xiaozhizhang.config.v1.CreateConfigRequest.value:type_name -> xiaozhizhang.config.v1.CreateConfigRequest.ValueEntry
	18, // 2: xiaozhizhang.config.v1.CreateConfigRequest.metadata:type_name -> xiaozhizhang.config.v1.CreateConfigRequest.MetadataEntry
	19, // 3: xiaozhizhang.config.v1.UpdateConfigRequest.value:type_name -> xiaozhizhang.config.v1.UpdateConfigRequest.ValueEntry
	20, // 4: xiaozhizhang.config.v1.UpdateConfigRequest.metadata:type_name -> xiaozhizhang.config.v1.UpdateConfigRequest.MetadataEntry
	10, // 5: xiaozhizhang.config.v1.ListConfigsForAdminResponse.content:type_name -> xiaozhizhang.config.v1.ConfigResponse
	21, // 6: xiaozhizhang.config.v1.ConfigResponse.value:type_name -> xiaozhizhang.config.v1.ConfigResponse.ValueEntry
	22, // 7: xiaozhizhang.config.v1.ConfigResponse.metadata:type_name -> xiaozhizhang.config.v1.ConfigResponse.MetadataEntry
	23, // 8: xiaozhizhang.config.v1.BatchGetConfigsResponse.configs:type_name -> xiaozhizhang.config.v1.BatchGetConfigsResponse.ConfigsEntry
	24, // 9: xiaozhizhang.config.v1.GetConfigsByPrefixResponse.configs:type_name -> xiaozhizhang.config.v1.GetConfigsByPrefixResponse.ConfigsEntry
	1,  // 10: xiaozhizhang.config.v1.CreateConfigRequest.ValueEntry.value:type_name -> xiaozhizhang.config.v1.ConfigValue
	1,  // 11: xiaozhizhang.config.v1.UpdateConfigRequest.ValueEntry.value:type_name -> xiaozhizhang.config.v1.ConfigValue
	1,  // 12: xiaozhizhang.config.v1.ConfigResponse.ValueEntry.value:type_name -> xiaozhizhang.config.v1.ConfigValue
	2,  // 13: xiaozhizhang.config.v1.ConfigService.CreateConfig:input_type -> xiaozhizhang.config.v1.CreateConfigRequest
	3,  // 14: xiaozhizhang.config.v1.ConfigService.UpdateConfig:input_type -> xiaozhizhang.config.v1.UpdateConfigRequest
	4,  // 15: xiaozhizhang.config.v1.ConfigService.DeleteConfig:input_type -> xiaozhizhang.config.v1.DeleteConfigRequest
	6,  // 16: xiaozhizhang.config.v1.ConfigService.GetConfigForAdmin:input_type -> xiaozhizhang.config.v1.GetConfigForAdminRequest
	7,  // 17: xiaozhizhang.config.v1.ConfigService.ListConfigsForAdmin:input_type -> xiaozhizhang.config.v1.ListConfigsForAdminRequest
	9,  // 18: xiaozhizhang.config.v1.ConfigService.UpdateConfigStatus:input_type -> xiaozhizhang.config.v1.UpdateConfigStatusRequest
	11, // 19: xiaozhizhang.config.v1.ConfigService.GetConfig:input_type -> xiaozhizhang.config.v1.GetConfigRequest
	13, // 20: xiaozhizhang.config.v1.ConfigService.BatchGetConfigs:input_type -> xiaozhizhang.config.v1.BatchGetConfigsRequest
	15, // 21: xiaozhizhang.config.v1.ConfigService.GetConfigsByPrefix:input_type -> xiaozhizhang.config.v1.GetConfigsByPrefixRequest
	10, // 22: xiaozhizhang.config.v1.ConfigService.CreateConfig:output_type -> xiaozhizhang.config.v1.ConfigResponse
	10, // 23: xiaozhizhang.config.v1.ConfigService.UpdateConfig:output_type -> xiaozhizhang.config.v1.ConfigResponse
	5,  // 24: xiaozhizhang.config.v1.ConfigService.DeleteConfig:output_type -> xiaozhizhang.config.v1.DeleteConfigResponse
	10, // 25: xiaozhizhang.config.v1.ConfigService.GetConfigForAdmin:output_type -> xiaozhizhang.config.v1.ConfigResponse
	8,  // 26: xiaozhizhang.config.v1.ConfigService.ListConfigsForAdmin:output_type -> xiaozhizhang.config.v1.ListConfigsForAdminResponse
	10, // 27: xiaozhizhang.config.v1.ConfigService.UpdateConfigStatus:output_type -> xiaozhizhang.config.v1.ConfigResponse
	12, // 28: xiaozhizhang.config.v1.ConfigService.GetConfig:output_type -> xiaozhizhang.config.v1.GetConfigResponse
	14, // 29: xiaozhizhang.config.v1.ConfigService.BatchGetConfigs:output_type -> xiaozhizhang.config.v1.BatchGetConfigsResponse
	16, // 30: xiaozhizhang.config.v1.ConfigService.GetConfigsByPrefix:output_type -> xiaozhizhang.config.v1.GetConfigsByPrefixResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
