// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.1
// source: shorturl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateShortLinkRequest 创建短链接请求
type CreateShortLinkRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DomainId         int64                  `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	TargetType       string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetConfigJson string                 `protobuf:"bytes,3,opt,name=target_config_json,json=targetConfigJson,proto3" json:"target_config_json,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Password         string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	MaxVisits        int64                  `protobuf:"varint,6,opt,name=max_visits,json=maxVisits,proto3" json:"max_visits,omitempty"`
	CodeLength       int32                  `protobuf:"varint,7,opt,name=code_length,json=codeLength,proto3" json:"code_length,omitempty"`
	CustomCode       string                 `protobuf:"bytes,8,opt,name=custom_code,json=customCode,proto3" json:"custom_code,omitempty"`
	Comment          string                 `protobuf:"bytes,9,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateShortLinkRequest) Reset() {
	*x = CreateShortLinkRequest{}
	mi := &file_shorturl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkRequest) ProtoMessage() {}

func (x *CreateShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortLinkRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *CreateShortLinkRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CreateShortLinkRequest) GetTargetConfigJson() string {
	if x != nil {
		return x.TargetConfigJson
	}
	return ""
}

func (x *CreateShortLinkRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CreateShortLinkRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateShortLinkRequest) GetMaxVisits() int64 {
	if x != nil {
		return x.MaxVisits
	}
	return 0
}

func (x *CreateShortLinkRequest) GetCodeLength() int32 {
	if x != nil {
		return x.CodeLength
	}
	return 0
}

func (x *CreateShortLinkRequest) GetCustomCode() string {
	if x != nil {
		return x.CustomCode
	}
	return ""
}

func (x *CreateShortLinkRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// CreateShortLinkResponse 创建短链接响应
type CreateShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkResponse) Reset() {
	*x = CreateShortLinkResponse{}
	mi := &file_shorturl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkResponse) ProtoMessage() {}

func (x *CreateShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortLinkResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateShortLinkResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateShortLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// GetShortLinkRequest 获取短链接请求
type GetShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinkRequest) Reset() {
	*x = GetShortLinkRequest{}
	mi := &file_shorturl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinkRequest) ProtoMessage() {}

func (x *GetShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinkRequest.ProtoReflect.Descriptor instead.
func (*GetShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *GetShortLinkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListShortLinksRequest 查询短链接列表请求
type ListShortLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      int64                  `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShortLinksRequest) Reset() {
	*x = ListShortLinksRequest{}
	mi := &file_shorturl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortLinksRequest) ProtoMessage() {}

func (x *ListShortLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortLinksRequest.ProtoReflect.Descriptor instead.
func (*ListShortLinksRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *ListShortLinksRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *ListShortLinksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShortLinksRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ListShortLinksResponse 查询短链接列表响应
type ListShortLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*ShortLinkInfo       `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShortLinksResponse) Reset() {
	*x = ListShortLinksResponse{}
	mi := &file_shorturl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortLinksResponse) ProtoMessage() {}

func (x *ListShortLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortLinksResponse.ProtoReflect.Descriptor instead.
func (*ListShortLinksResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{4}
}

func (x *ListShortLinksResponse) GetLinks() []*ShortLinkInfo {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListShortLinksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ShortLinkInfo 短链接信息
type ShortLinkInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId         int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Domain           string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Code             string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	ShortUrl         string                 `protobuf:"bytes,5,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	TargetType       string                 `protobuf:"bytes,6,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetConfigJson string                 `protobuf:"bytes,7,opt,name=target_config_json,json=targetConfigJson,proto3" json:"target_config_json,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	MaxVisits        int64                  `protobuf:"varint,9,opt,name=max_visits,json=maxVisits,proto3" json:"max_visits,omitempty"`
	VisitCount       int64                  `protobuf:"varint,10,opt,name=visit_count,json=visitCount,proto3" json:"visit_count,omitempty"`
	SuccessCount     int64                  `protobuf:"varint,11,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	HasPassword      bool                   `protobuf:"varint,12,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	Enabled          bool                   `protobuf:"varint,13,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Comment          string                 `protobuf:"bytes,14,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ShortLinkInfo) Reset() {
	*x = ShortLinkInfo{}
	mi := &file_shorturl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortLinkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLinkInfo) ProtoMessage() {}

func (x *ShortLinkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLinkInfo.ProtoReflect.Descriptor instead.
func (*ShortLinkInfo) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{5}
}

func (x *ShortLinkInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShortLinkInfo) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *ShortLinkInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ShortLinkInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShortLinkInfo) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortLinkInfo) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ShortLinkInfo) GetTargetConfigJson() string {
	if x != nil {
		return x.TargetConfigJson
	}
	return ""
}

func (x *ShortLinkInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ShortLinkInfo) GetMaxVisits() int64 {
	if x != nil {
		return x.MaxVisits
	}
	return 0
}

func (x *ShortLinkInfo) GetVisitCount() int64 {
	if x != nil {
		return x.VisitCount
	}
	return 0
}

func (x *ShortLinkInfo) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ShortLinkInfo) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

func (x *ShortLinkInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShortLinkInfo) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ShortLinkInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ShortLinkInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ResolveRequest 解析短链接请求
type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_shorturl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ResolveRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResolveRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// ResolveResponse 解析短链接响应
type ResolveResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetType       string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetConfigJson string                 `protobuf:"bytes,2,opt,name=target_config_json,json=targetConfigJson,proto3" json:"target_config_json,omitempty"`
	Action           string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "redirect" 或 "landing_page"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_shorturl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveResponse) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ResolveResponse) GetTargetConfigJson() string {
	if x != nil {
		return x.TargetConfigJson
	}
	return ""
}

func (x *ResolveResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// ReportSuccessRequest 上报成功请求
type ReportSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AttrsJson     string                 `protobuf:"bytes,3,opt,name=attrs_json,json=attrsJson,proto3" json:"attrs_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSuccessRequest) Reset() {
	*x = ReportSuccessRequest{}
	mi := &file_shorturl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSuccessRequest) ProtoMessage() {}

func (x *ReportSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSuccessRequest.ProtoReflect.Descriptor instead.
func (*ReportSuccessRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{8}
}

func (x *ReportSuccessRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportSuccessRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReportSuccessRequest) GetAttrsJson() string {
	if x != nil {
		return x.AttrsJson
	}
	return ""
}

// ReportSuccessResponse 上报成功响应
type ReportSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSuccessResponse) Reset() {
	*x = ReportSuccessResponse{}
	mi := &file_shorturl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSuccessResponse) ProtoMessage() {}

func (x *ReportSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSuccessResponse.ProtoReflect.Descriptor instead.
func (*ReportSuccessResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{9}
}

func (x *ReportSuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportSuccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shorturl_proto protoreflect.FileDescriptor

const file_shorturl_proto_rawDesc = "" +
	"\n" +
	"\x0eshorturl.proto\x12\vshorturl.v1\"\xba\x02\n" +
	"\x16CreateShortLinkRequest\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\x03R\bdomainId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12,\n" +
	"\x12target_config_json\x18\x03 \x01(\tR\x10targetConfigJson\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"max_visits\x18\x06 \x01(\x03R\tmaxVisits\x12\x1f\n" +
	"\vcode_length\x18\a \x01(\x05R\n" +
	"codeLength\x12\x1f\n" +
	"\vcustom_code\x18\b \x01(\tR\n" +
	"customCode\x12\x18\n" +
	"\acomment\x18\t \x01(\tR\acomment\"Z\n" +
	"\x17CreateShortLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\"%\n" +
	"\x13GetShortLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\\\n" +
	"\x15ListShortLinksRequest\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\x03R\bdomainId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"`\n" +
	"\x16ListShortLinksResponse\x120\n" +
	"\x05links\x18\x01 \x03(\v2\x1a.shorturl.v1.ShortLinkInfoR\x05links\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xed\x03\n" +
	"\rShortLinkInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1b\n" +
	"\tshort_url\x18\x05 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vtarget_type\x18\x06 \x01(\tR\n" +
	"targetType\x12,\n" +
	"\x12target_config_json\x18\a \x01(\tR\x10targetConfigJson\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"max_visits\x18\t \x01(\x03R\tmaxVisits\x12\x1f\n" +
	"\vvisit_count\x18\n" +
	" \x01(\x03R\n" +
	"visitCount\x12#\n" +
	"\rsuccess_count\x18\v \x01(\x03R\fsuccessCount\x12!\n" +
	"\fhas_password\x18\f \x01(\bR\vhasPassword\x12\x18\n" +
	"\aenabled\x18\r \x01(\bR\aenabled\x12\x18\n" +
	"\acomment\x18\x0e \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\x03R\tupdatedAt\"T\n" +
	"\x0eResolveRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"x\n" +
	"\x0fResolveResponse\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12,\n" +
	"\x12target_config_json\x18\x02 \x01(\tR\x10targetConfigJson\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"d\n" +
	"\x14ReportSuccessRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"attrs_json\x18\x03 \x01(\tR\tattrsJson\"K\n" +
	"\x15ReportSuccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb6\x03\n" +
	"\x0fShortURLService\x12\\\n" +
	"\x0fCreateShortLink\x12#.shorturl.v1.CreateShortLinkRequest\x1a$.shorturl.v1.CreateShortLinkResponse\x12L\n" +
	"\fGetShortLink\x12 .shorturl.v1.GetShortLinkRequest\x1a\x1a.shorturl.v1.ShortLinkInfo\x12Y\n" +
	"\x0eListShortLinks\x12\".shorturl.v1.ListShortLinksRequest\x1a#.shorturl.v1.ListShortLinksResponse\x12D\n" +
	"\aResolve\x12\x1b.shorturl.v1.ResolveRequest\x1a\x1c.shorturl.v1.ResolveResponse\x12V\n" +
	"\rReportSuccess\x12!.shorturl.v1.ReportSuccessRequest\x1a\".shorturl.v1.ReportSuccessResponseB(Z&xiaozhizhang/system/shorturl/api/protob\x06proto3"

var (
	file_shorturl_proto_rawDescOnce sync.Once
	file_shorturl_proto_rawDescData []byte
)

func file_shorturl_proto_rawDescGZIP() []byte {
	file_shorturl_proto_rawDescOnce.Do(func() {
		file_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturl_proto_rawDesc), len(file_shorturl_proto_rawDesc)))
	})
	return file_shorturl_proto_rawDescData
}

var file_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shorturl_proto_goTypes = []any{
	(*CreateShortLinkRequest)(nil),  // 0: shorturl.v1.CreateShortLinkRequest
	(*CreateShortLinkResponse)(nil), // 1: shorturl.v1.CreateShortLinkResponse
	(*GetShortLinkRequest)(nil),     // 2: shorturl.v1.GetShortLinkRequest
	(*ListShortLinksRequest)(nil),   // 3: shorturl.v1.ListShortLinksRequest
	(*ListShortLinksResponse)(nil),  // 4: shorturl.v1.ListShortLinksResponse
	(*ShortLinkInfo)(nil),           // 5: shorturl.v1.ShortLinkInfo
	(*ResolveRequest)(nil),          // 6: shorturl.v1.ResolveRequest
	(*ResolveResponse)(nil),         // 7: shorturl.v1.ResolveResponse
	(*ReportSuccessRequest)(nil),    // 8: shorturl.v1.ReportSuccessRequest
	(*ReportSuccessResponse)(nil),   // 9: shorturl.v1.ReportSuccessResponse
}
var file_shorturl_proto_depIdxs = []int32{
	5, // 0: shorturl.v1.ListShortLinksResponse.links:type_name -> shorturl.v1.ShortLinkInfo
	0, // 1: shorturl.v1.ShortURLService.CreateShortLink:input_type -> shorturl.v1.CreateShortLinkRequest
	2, // 2: shorturl.v1.ShortURLService.GetShortLink:input_type -> shorturl.v1.GetShortLinkRequest
	3, // 3: shorturl.v1.ShortURLService.ListShortLinks:input_type -> shorturl.v1.ListShortLinksRequest
	6, // 4: shorturl.v1.ShortURLService.Resolve:input_type -> shorturl.v1.ResolveRequest
	8, // 5: shorturl.v1.ShortURLService.ReportSuccess:input_type -> shorturl.v1.ReportSuccessRequest
	1, // 6: shorturl.v1.ShortURLService.CreateShortLink:output_type -> shorturl.v1.CreateShortLinkResponse
	5, // 7: shorturl.v1.ShortURLService.GetShortLink:output_type -> shorturl.v1.ShortLinkInfo
	4, // 8: shorturl.v1.ShortURLService.ListShortLinks:output_type -> shorturl.v1.ListShortLinksResponse
	7, // 9: shorturl.v1.ShortURLService.Resolve:output_type -> shorturl.v1.ResolveResponse
	9, // 10: shorturl.v1.ShortURLService.ReportSuccess:output_type -> shorturl.v1.ReportSuccessResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shorturl_proto_init() }
func file_shorturl_proto_init() {
	if File_shorturl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturl_proto_rawDesc), len(file_shorturl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shorturl_proto_goTypes,
		DependencyIndexes: file_shorturl_proto_depIdxs,
		MessageInfos:      file_shorturl_proto_msgTypes,
	}.Build()
	File_shorturl_proto = out.File
	file_shorturl_proto_goTypes = nil
	file_shorturl_proto_depIdxs = nil
}
