// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.1
// source: system/registry/api/proto/registry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterInstanceRequest 注册实例请求
type RegisterInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     int64                  `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`      // 服务 ID（必填）
	InstanceKey   string                 `protobuf:"bytes,2,opt,name=instance_key,json=instanceKey,proto3" json:"instance_key,omitempty"` // 实例唯一标识（可为空，服务端生成）
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`                                    // 环境（必填）
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`                                  // 主机地址（必填）
	Endpoint      string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                          // 服务端点（必填）
	MetaJson      string                 `protobuf:"bytes,6,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`          // 实例元数据（JSON 字符串）
	TtlSeconds    int64                  `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`   // TTL 秒数（默认 60）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInstanceRequest) Reset() {
	*x = RegisterInstanceRequest{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceRequest) ProtoMessage() {}

func (x *RegisterInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceRequest.ProtoReflect.Descriptor instead.
func (*RegisterInstanceRequest) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterInstanceRequest) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *RegisterInstanceRequest) GetInstanceKey() string {
	if x != nil {
		return x.InstanceKey
	}
	return ""
}

func (x *RegisterInstanceRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *RegisterInstanceRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterInstanceRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterInstanceRequest) GetMetaJson() string {
	if x != nil {
		return x.MetaJson
	}
	return ""
}

func (x *RegisterInstanceRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// RegisterInstanceResponse 注册实例响应
type RegisterInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceKey   string                 `protobuf:"bytes,1,opt,name=instance_key,json=instanceKey,proto3" json:"instance_key,omitempty"` // 实例唯一标识
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`      // 过期时间戳（unix 秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInstanceResponse) Reset() {
	*x = RegisterInstanceResponse{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceResponse) ProtoMessage() {}

func (x *RegisterInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceResponse.ProtoReflect.Descriptor instead.
func (*RegisterInstanceResponse) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterInstanceResponse) GetInstanceKey() string {
	if x != nil {
		return x.InstanceKey
	}
	return ""
}

func (x *RegisterInstanceResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// DeregisterInstanceRequest 注销实例请求
type DeregisterInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     int64                  `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`      // 服务 ID（必填）
	InstanceKey   string                 `protobuf:"bytes,2,opt,name=instance_key,json=instanceKey,proto3" json:"instance_key,omitempty"` // 实例唯一标识（必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterInstanceRequest) Reset() {
	*x = DeregisterInstanceRequest{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterInstanceRequest) ProtoMessage() {}

func (x *DeregisterInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterInstanceRequest) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterInstanceRequest) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *DeregisterInstanceRequest) GetInstanceKey() string {
	if x != nil {
		return x.InstanceKey
	}
	return ""
}

// DeregisterInstanceResponse 注销实例响应
type DeregisterInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterInstanceResponse) Reset() {
	*x = DeregisterInstanceResponse{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterInstanceResponse) ProtoMessage() {}

func (x *DeregisterInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterInstanceResponse.ProtoReflect.Descriptor instead.
func (*DeregisterInstanceResponse) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterInstanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeregisterInstanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HeartbeatRequest 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     int64                  `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`      // 服务 ID（必填）
	InstanceKey   string                 `protobuf:"bytes,2,opt,name=instance_key,json=instanceKey,proto3" json:"instance_key,omitempty"` // 实例唯一标识（必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *HeartbeatRequest) GetInstanceKey() string {
	if x != nil {
		return x.InstanceKey
	}
	return ""
}

// HeartbeatResponse 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt     int64                  `protobuf:"varint,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // 新的过期时间戳（unix 秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// ListServicesRequest 获取服务列表请求
type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"` // 项目名（可选，过滤条件）
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`         // 环境（可选，过滤条件）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{6}
}

func (x *ListServicesRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListServicesRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// ListServicesResponse 获取服务列表响应
type ListServicesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Services      []*ServiceWithInstances `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"` // 服务列表（包含在线实例）
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`      // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{7}
}

func (x *ListServicesResponse) GetServices() []*ServiceWithInstances {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListServicesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetServiceByIDRequest 获取服务详情请求
type GetServiceByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 服务 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceByIDRequest) Reset() {
	*x = GetServiceByIDRequest{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceByIDRequest) ProtoMessage() {}

func (x *GetServiceByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceByIDRequest.ProtoReflect.Descriptor instead.
func (*GetServiceByIDRequest) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{8}
}

func (x *GetServiceByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetServiceByIDResponse 获取服务详情响应
type GetServiceByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceWithInstances  `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // 服务详情（包含在线实例）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceByIDResponse) Reset() {
	*x = GetServiceByIDResponse{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceByIDResponse) ProtoMessage() {}

func (x *GetServiceByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceByIDResponse.ProtoReflect.Descriptor instead.
func (*GetServiceByIDResponse) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{9}
}

func (x *GetServiceByIDResponse) GetService() *ServiceWithInstances {
	if x != nil {
		return x.Service
	}
	return nil
}

// Service 服务定义
type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 服务 ID
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`                       // 项目名
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                             // 服务名
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`                           // 负责人
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`               // 描述
	SpecJson      string                 `protobuf:"bytes,6,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`     // 服务规格（JSON 字符串）
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间（unix 秒）
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间（unix 秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{10}
}

func (x *Service) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Service) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

func (x *Service) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Service) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Instance 实例信息
type Instance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                    // 实例 ID
	ServiceId       int64                  `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`                     // 服务 ID
	InstanceKey     string                 `protobuf:"bytes,3,opt,name=instance_key,json=instanceKey,proto3" json:"instance_key,omitempty"`                // 实例唯一标识
	Env             string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`                                                   // 环境
	Host            string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`                                                 // 主机地址
	Endpoint        string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                         // 服务端点
	MetaJson        string                 `protobuf:"bytes,7,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`                         // 实例元数据（JSON 字符串）
	TtlSeconds      int64                  `protobuf:"varint,8,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`                  // TTL 秒数
	LastHeartbeatAt int64                  `protobuf:"varint,9,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"` // 最后心跳时间（unix 秒）
	CreatedAt       int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                    // 创建时间（unix 秒）
	UpdatedAt       int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                    // 更新时间（unix 秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{11}
}

func (x *Instance) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Instance) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *Instance) GetInstanceKey() string {
	if x != nil {
		return x.InstanceKey
	}
	return ""
}

func (x *Instance) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Instance) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Instance) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Instance) GetMetaJson() string {
	if x != nil {
		return x.MetaJson
	}
	return ""
}

func (x *Instance) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Instance) GetLastHeartbeatAt() int64 {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return 0
}

func (x *Instance) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Instance) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ServiceWithInstances 服务及其在线实例
type ServiceWithInstances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`     // 服务定义
	Instances     []*Instance            `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"` // 在线实例列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceWithInstances) Reset() {
	*x = ServiceWithInstances{}
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceWithInstances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceWithInstances) ProtoMessage() {}

func (x *ServiceWithInstances) ProtoReflect() protoreflect.Message {
	mi := &file_system_registry_api_proto_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceWithInstances.ProtoReflect.Descriptor instead.
func (*ServiceWithInstances) Descriptor() ([]byte, []int) {
	return file_system_registry_api_proto_registry_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceWithInstances) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceWithInstances) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

var File_system_registry_api_proto_registry_proto protoreflect.FileDescriptor

const file_system_registry_api_proto_registry_proto_rawDesc = "" +
	"\n" +
	"(system/registry/api/proto/registry.proto\x12\x18xiaozhizhang.registry.v1\"\xdb\x01\n" +
	"\x17RegisterInstanceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x03R\tserviceId\x12!\n" +
	"\finstance_key\x18\x02 \x01(\tR\vinstanceKey\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tmeta_json\x18\x06 \x01(\tR\bmetaJson\x12\x1f\n" +
	"\vttl_seconds\x18\a \x01(\x03R\n" +
	"ttlSeconds\"\\\n" +
	"\x18RegisterInstanceResponse\x12!\n" +
	"\finstance_key\x18\x01 \x01(\tR\vinstanceKey\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"]\n" +
	"\x19DeregisterInstanceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x03R\tserviceId\x12!\n" +
	"\finstance_key\x18\x02 \x01(\tR\vinstanceKey\"P\n" +
	"\x1aDeregisterInstanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x03R\tserviceId\x12!\n" +
	"\finstance_key\x18\x02 \x01(\tR\vinstanceKey\"2\n" +
	"\x11HeartbeatResponse\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\x03R\texpiresAt\"A\n" +
	"\x13ListServicesRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\"x\n" +
	"\x14ListServicesResponse\x12J\n" +
	"\bservices\x18\x01 \x03(\v2..xiaozhizhang.registry.v1.ServiceWithInstancesR\bservices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"'\n" +
	"\x15GetServiceByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"b\n" +
	"\x16GetServiceByIDResponse\x12H\n" +
	"\aservice\x18\x01 \x01(\v2..xiaozhizhang.registry.v1.ServiceWithInstancesR\aservice\"\xda\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tspec_json\x18\x06 \x01(\tR\bspecJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xc6\x02\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x03R\tserviceId\x12!\n" +
	"\finstance_key\x18\x03 \x01(\tR\vinstanceKey\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tmeta_json\x18\a \x01(\tR\bmetaJson\x12\x1f\n" +
	"\vttl_seconds\x18\b \x01(\x03R\n" +
	"ttlSeconds\x12*\n" +
	"\x11last_heartbeat_at\x18\t \x01(\x03R\x0flastHeartbeatAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\x95\x01\n" +
	"\x14ServiceWithInstances\x12;\n" +
	"\aservice\x18\x01 \x01(\v2!.xiaozhizhang.registry.v1.ServiceR\aservice\x12@\n" +
	"\tinstances\x18\x02 \x03(\v2\".xiaozhizhang.registry.v1.InstanceR\tinstances2\xe1\x04\n" +
	"\x0fRegistryService\x12y\n" +
	"\x10RegisterInstance\x121.xiaozhizhang.registry.v1.RegisterInstanceRequest\x1a2.xiaozhizhang.registry.v1.RegisterInstanceResponse\x12\x7f\n" +
	"\x12DeregisterInstance\x123.xiaozhizhang.registry.v1.DeregisterInstanceRequest\x1a4.xiaozhizhang.registry.v1.DeregisterInstanceResponse\x12n\n" +
	"\x0fHeartbeatStream\x12*.xiaozhizhang.registry.v1.HeartbeatRequest\x1a+.xiaozhizhang.registry.v1.HeartbeatResponse(\x010\x01\x12m\n" +
	"\fListServices\x12-.xiaozhizhang.registry.v1.ListServicesRequest\x1a..xiaozhizhang.registry.v1.ListServicesResponse\x12s\n" +
	"\x0eGetServiceByID\x12/.xiaozhizhang.registry.v1.GetServiceByIDRequest\x1a0.xiaozhizhang.registry.v1.GetServiceByIDResponseB.Z,xiaozhizhang/system/registry/api/proto;protob\x06proto3"

var (
	file_system_registry_api_proto_registry_proto_rawDescOnce sync.Once
	file_system_registry_api_proto_registry_proto_rawDescData []byte
)

func file_system_registry_api_proto_registry_proto_rawDescGZIP() []byte {
	file_system_registry_api_proto_registry_proto_rawDescOnce.Do(func() {
		file_system_registry_api_proto_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_registry_api_proto_registry_proto_rawDesc), len(file_system_registry_api_proto_registry_proto_rawDesc)))
	})
	return file_system_registry_api_proto_registry_proto_rawDescData
}

var file_system_registry_api_proto_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_system_registry_api_proto_registry_proto_goTypes = []any{
	(*RegisterInstanceRequest)(nil),    // 0: xiaozhizhang.registry.v1.RegisterInstanceRequest
	(*RegisterInstanceResponse)(nil),   // 1: xiaozhizhang.registry.v1.RegisterInstanceResponse
	(*DeregisterInstanceRequest)(nil),  // 2: xiaozhizhang.registry.v1.DeregisterInstanceRequest
	(*DeregisterInstanceResponse)(nil), // 3: xiaozhizhang.registry.v1.DeregisterInstanceResponse
	(*HeartbeatRequest)(nil),           // 4: xiaozhizhang.registry.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 5: xiaozhizhang.registry.v1.HeartbeatResponse
	(*ListServicesRequest)(nil),        // 6: xiaozhizhang.registry.v1.ListServicesRequest
	(*ListServicesResponse)(nil),       // 7: xiaozhizhang.registry.v1.ListServicesResponse
	(*GetServiceByIDRequest)(nil),      // 8: xiaozhizhang.registry.v1.GetServiceByIDRequest
	(*GetServiceByIDResponse)(nil),     // 9: xiaozhizhang.registry.v1.GetServiceByIDResponse
	(*Service)(nil),                    // 10: xiaozhizhang.registry.v1.Service
	(*Instance)(nil),                   // 11: xiaozhizhang.registry.v1.Instance
	(*ServiceWithInstances)(nil),       // 12: xiaozhizhang.registry.v1.ServiceWithInstances
}
var file_system_registry_api_proto_registry_proto_depIdxs = []int32{
	12, // 0: xiaozhizhang.registry.v1.ListServicesResponse.services:type_name -> xiaozhizhang.registry.v1.ServiceWithInstances
	12, // 1: xiaozhizhang.registry.v1.GetServiceByIDResponse.service:type_name -> xiaozhizhang.registry.v1.ServiceWithInstances
	10, // 2: xiaozhizhang.registry.v1.ServiceWithInstances.service:type_name -> xiaozhizhang.registry.v1.Service
	11, // 3: xiaozhizhang.registry.v1.ServiceWithInstances.instances:type_name -> xiaozhizhang.registry.v1.Instance
	0,  // 4: xiaozhizhang.registry.v1.RegistryService.RegisterInstance:input_type -> xiaozhizhang.registry.v1.RegisterInstanceRequest
	2,  // 5: xiaozhizhang.registry.v1.RegistryService.DeregisterInstance:input_type -> xiaozhizhang.registry.v1.DeregisterInstanceRequest
	4,  // 6: xiaozhizhang.registry.v1.RegistryService.HeartbeatStream:input_type -> xiaozhizhang.registry.v1.HeartbeatRequest
	6,  // 7: xiaozhizhang.registry.v1.RegistryService.ListServices:input_type -> xiaozhizhang.registry.v1.ListServicesRequest
	8,  // 8: xiaozhizhang.registry.v1.RegistryService.GetServiceByID:input_type -> xiaozhizhang.registry.v1.GetServiceByIDRequest
	1,  // 9: xiaozhizhang.registry.v1.RegistryService.RegisterInstance:output_type -> xiaozhizhang.registry.v1.RegisterInstanceResponse
	3,  // 10: xiaozhizhang.registry.v1.RegistryService.DeregisterInstance:output_type -> xiaozhizhang.registry.v1.DeregisterInstanceResponse
	5,  // 11: xiaozhizhang.registry.v1.RegistryService.HeartbeatStream:output_type -> xiaozhizhang.registry.v1.HeartbeatResponse
	7,  // 12: xiaozhizhang.registry.v1.RegistryService.ListServices:output_type -> xiaozhizhang.registry.v1.ListServicesResponse
	9,  // 13: xiaozhizhang.registry.v1.RegistryService.GetServiceByID:output_type -> xiaozhizhang.registry.v1.GetServiceByIDResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_system_registry_api_proto_registry_proto_init() }
func file_system_registry_api_proto_registry_proto_init() {
	if File_system_registry_api_proto_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_registry_api_proto_registry_proto_rawDesc), len(file_system_registry_api_proto_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_registry_api_proto_registry_proto_goTypes,
		DependencyIndexes: file_system_registry_api_proto_registry_proto_depIdxs,
		MessageInfos:      file_system_registry_api_proto_registry_proto_msgTypes,
	}.Build()
	File_system_registry_api_proto_registry_proto = out.File
	file_system_registry_api_proto_registry_proto_goTypes = nil
	file_system_registry_api_proto_registry_proto_depIdxs = nil
}
