// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.1
// source: system/registry/api/proto/registry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryService_RegisterInstance_FullMethodName   = "/xiaozhizhang.registry.v1.RegistryService/RegisterInstance"
	RegistryService_DeregisterInstance_FullMethodName = "/xiaozhizhang.registry.v1.RegistryService/DeregisterInstance"
	RegistryService_HeartbeatStream_FullMethodName    = "/xiaozhizhang.registry.v1.RegistryService/HeartbeatStream"
	RegistryService_ListServices_FullMethodName       = "/xiaozhizhang.registry.v1.RegistryService/ListServices"
	RegistryService_GetServiceByID_FullMethodName     = "/xiaozhizhang.registry.v1.RegistryService/GetServiceByID"
)

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RegistryService 注册中心服务
type RegistryServiceClient interface {
	// RegisterInstance 注册实例（上线）
	RegisterInstance(ctx context.Context, in *RegisterInstanceRequest, opts ...grpc.CallOption) (*RegisterInstanceResponse, error)
	// DeregisterInstance 注销实例（下线）
	DeregisterInstance(ctx context.Context, in *DeregisterInstanceRequest, opts ...grpc.CallOption) (*DeregisterInstanceResponse, error)
	// HeartbeatStream 心跳流（双向流：客户端持续发送心跳，服务端逐条响应续租结果）
	HeartbeatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// ListServices 获取服务列表（包含在线实例）
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// GetServiceByID 根据 ID 获取服务详情（包含在线实例）
	GetServiceByID(ctx context.Context, in *GetServiceByIDRequest, opts ...grpc.CallOption) (*GetServiceByIDResponse, error)
}

type registryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryServiceClient(cc grpc.ClientConnInterface) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) RegisterInstance(ctx context.Context, in *RegisterInstanceRequest, opts ...grpc.CallOption) (*RegisterInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterInstanceResponse)
	err := c.cc.Invoke(ctx, RegistryService_RegisterInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) DeregisterInstance(ctx context.Context, in *DeregisterInstanceRequest, opts ...grpc.CallOption) (*DeregisterInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterInstanceResponse)
	err := c.cc.Invoke(ctx, RegistryService_DeregisterInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) HeartbeatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RegistryService_ServiceDesc.Streams[0], RegistryService_HeartbeatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RegistryService_HeartbeatStreamClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *registryServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, RegistryService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetServiceByID(ctx context.Context, in *GetServiceByIDRequest, opts ...grpc.CallOption) (*GetServiceByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceByIDResponse)
	err := c.cc.Invoke(ctx, RegistryService_GetServiceByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
// All implementations must embed UnimplementedRegistryServiceServer
// for forward compatibility.
//
// RegistryService 注册中心服务
type RegistryServiceServer interface {
	// RegisterInstance 注册实例（上线）
	RegisterInstance(context.Context, *RegisterInstanceRequest) (*RegisterInstanceResponse, error)
	// DeregisterInstance 注销实例（下线）
	DeregisterInstance(context.Context, *DeregisterInstanceRequest) (*DeregisterInstanceResponse, error)
	// HeartbeatStream 心跳流（双向流：客户端持续发送心跳，服务端逐条响应续租结果）
	HeartbeatStream(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// ListServices 获取服务列表（包含在线实例）
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// GetServiceByID 根据 ID 获取服务详情（包含在线实例）
	GetServiceByID(context.Context, *GetServiceByIDRequest) (*GetServiceByIDResponse, error)
	mustEmbedUnimplementedRegistryServiceServer()
}

// UnimplementedRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryServiceServer struct{}

func (UnimplementedRegistryServiceServer) RegisterInstance(context.Context, *RegisterInstanceRequest) (*RegisterInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterInstance not implemented")
}
func (UnimplementedRegistryServiceServer) DeregisterInstance(context.Context, *DeregisterInstanceRequest) (*DeregisterInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterInstance not implemented")
}
func (UnimplementedRegistryServiceServer) HeartbeatStream(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method HeartbeatStream not implemented")
}
func (UnimplementedRegistryServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedRegistryServiceServer) GetServiceByID(context.Context, *GetServiceByIDRequest) (*GetServiceByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceByID not implemented")
}
func (UnimplementedRegistryServiceServer) mustEmbedUnimplementedRegistryServiceServer() {}
func (UnimplementedRegistryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServiceServer will
// result in compilation errors.
type UnsafeRegistryServiceServer interface {
	mustEmbedUnimplementedRegistryServiceServer()
}

func RegisterRegistryServiceServer(s grpc.ServiceRegistrar, srv RegistryServiceServer) {
	// If the following call pancis, it indicates UnimplementedRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryService_ServiceDesc, srv)
}

func _RegistryService_RegisterInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).RegisterInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_RegisterInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).RegisterInstance(ctx, req.(*RegisterInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_DeregisterInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).DeregisterInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_DeregisterInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).DeregisterInstance(ctx, req.(*DeregisterInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_HeartbeatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RegistryServiceServer).HeartbeatStream(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RegistryService_HeartbeatStreamServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _RegistryService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetServiceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetServiceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetServiceByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetServiceByID(ctx, req.(*GetServiceByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryService_ServiceDesc is the grpc.ServiceDesc for RegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xiaozhizhang.registry.v1.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterInstance",
			Handler:    _RegistryService_RegisterInstance_Handler,
		},
		{
			MethodName: "DeregisterInstance",
			Handler:    _RegistryService_DeregisterInstance_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _RegistryService_ListServices_Handler,
		},
		{
			MethodName: "GetServiceByID",
			Handler:    _RegistryService_GetServiceByID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HeartbeatStream",
			Handler:       _RegistryService_HeartbeatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "system/registry/api/proto/registry.proto",
}
