// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.1
// source: system/user/api/proto/user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientAuthService_AuthenticateClient_FullMethodName = "/xiaozhizhang.user.v1.ClientAuthService/AuthenticateClient"
	ClientAuthService_RenewToken_FullMethodName         = "/xiaozhizhang.user.v1.ClientAuthService/RenewToken"
)

// ClientAuthServiceClient is the client API for ClientAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientAuthService 客户端认证服务（gRPC 对外接口）
type ClientAuthServiceClient interface {
	// AuthenticateClient 客户端认证，返回 JWT token
	AuthenticateClient(ctx context.Context, in *AuthenticateClientRequest, opts ...grpc.CallOption) (*AuthenticateClientResponse, error)
	// RenewToken 续期 token（在未过期时延长有效期）
	RenewToken(ctx context.Context, in *RenewTokenRequest, opts ...grpc.CallOption) (*RenewTokenResponse, error)
}

type clientAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientAuthServiceClient(cc grpc.ClientConnInterface) ClientAuthServiceClient {
	return &clientAuthServiceClient{cc}
}

func (c *clientAuthServiceClient) AuthenticateClient(ctx context.Context, in *AuthenticateClientRequest, opts ...grpc.CallOption) (*AuthenticateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateClientResponse)
	err := c.cc.Invoke(ctx, ClientAuthService_AuthenticateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAuthServiceClient) RenewToken(ctx context.Context, in *RenewTokenRequest, opts ...grpc.CallOption) (*RenewTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewTokenResponse)
	err := c.cc.Invoke(ctx, ClientAuthService_RenewToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientAuthServiceServer is the server API for ClientAuthService service.
// All implementations must embed UnimplementedClientAuthServiceServer
// for forward compatibility.
//
// ClientAuthService 客户端认证服务（gRPC 对外接口）
type ClientAuthServiceServer interface {
	// AuthenticateClient 客户端认证，返回 JWT token
	AuthenticateClient(context.Context, *AuthenticateClientRequest) (*AuthenticateClientResponse, error)
	// RenewToken 续期 token（在未过期时延长有效期）
	RenewToken(context.Context, *RenewTokenRequest) (*RenewTokenResponse, error)
	mustEmbedUnimplementedClientAuthServiceServer()
}

// UnimplementedClientAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientAuthServiceServer struct{}

func (UnimplementedClientAuthServiceServer) AuthenticateClient(context.Context, *AuthenticateClientRequest) (*AuthenticateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateClient not implemented")
}
func (UnimplementedClientAuthServiceServer) RenewToken(context.Context, *RenewTokenRequest) (*RenewTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewToken not implemented")
}
func (UnimplementedClientAuthServiceServer) mustEmbedUnimplementedClientAuthServiceServer() {}
func (UnimplementedClientAuthServiceServer) testEmbeddedByValue()                           {}

// UnsafeClientAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientAuthServiceServer will
// result in compilation errors.
type UnsafeClientAuthServiceServer interface {
	mustEmbedUnimplementedClientAuthServiceServer()
}

func RegisterClientAuthServiceServer(s grpc.ServiceRegistrar, srv ClientAuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientAuthService_ServiceDesc, srv)
}

func _ClientAuthService_AuthenticateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAuthServiceServer).AuthenticateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAuthService_AuthenticateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAuthServiceServer).AuthenticateClient(ctx, req.(*AuthenticateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAuthService_RenewToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAuthServiceServer).RenewToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAuthService_RenewToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAuthServiceServer).RenewToken(ctx, req.(*RenewTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientAuthService_ServiceDesc is the grpc.ServiceDesc for ClientAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xiaozhizhang.user.v1.ClientAuthService",
	HandlerType: (*ClientAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateClient",
			Handler:    _ClientAuthService_AuthenticateClient_Handler,
		},
		{
			MethodName: "RenewToken",
			Handler:    _ClientAuthService_RenewToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/user/api/proto/user.proto",
}
