// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.1
// source: workflow.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateDefRequest 创建工作流定义请求
type CreateDefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                      // 工作流编码（必填）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // 工作流名称（必填）
	DagJson       string                 `protobuf:"bytes,3,opt,name=dag_json,json=dagJson,proto3" json:"dag_json,omitempty"` // DAG 定义 JSON（必填）
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`               // 版本号，默认 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDefRequest) Reset() {
	*x = CreateDefRequest{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDefRequest) ProtoMessage() {}

func (x *CreateDefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDefRequest.ProtoReflect.Descriptor instead.
func (*CreateDefRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDefRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateDefRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDefRequest) GetDagJson() string {
	if x != nil {
		return x.DagJson
	}
	return ""
}

func (x *CreateDefRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// CreateDefResponse 创建工作流定义响应
type CreateDefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefId         int64                  `protobuf:"varint,1,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"` // 定义 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDefResponse) Reset() {
	*x = CreateDefResponse{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDefResponse) ProtoMessage() {}

func (x *CreateDefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDefResponse.ProtoReflect.Descriptor instead.
func (*CreateDefResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDefResponse) GetDefId() int64 {
	if x != nil {
		return x.DefId
	}
	return 0
}

// StartWorkflowRequest 启动工作流请求
type StartWorkflowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DefCode         string                 `protobuf:"bytes,1,opt,name=def_code,json=defCode,proto3" json:"def_code,omitempty"`                           // 工作流定义编码（必填）
	InitialDataJson string                 `protobuf:"bytes,2,opt,name=initial_data_json,json=initialDataJson,proto3" json:"initial_data_json,omitempty"` // 初始数据 JSON，可为空 "{}"
	Env             string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`                                                  // 环境标识（如 dev/prod/test），用于 Executor 任务隔离，空则用进程默认环境
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *StartWorkflowRequest) GetDefCode() string {
	if x != nil {
		return x.DefCode
	}
	return ""
}

func (x *StartWorkflowRequest) GetInitialDataJson() string {
	if x != nil {
		return x.InitialDataJson
	}
	return ""
}

func (x *StartWorkflowRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// StartWorkflowResponse 启动工作流响应
type StartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int64                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 工作流实例 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *StartWorkflowResponse) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

// ReportNodeCompletedRequest 报告节点完成请求
type ReportNodeCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int64                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 工作流实例 ID（必填）
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`              // 节点 ID（必填）
	OutputJson    string                 `protobuf:"bytes,3,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`  // 节点输出 JSON，可为空 "{}"
	Env           string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`                                  // 环境标识（如 dev/prod/test），用于后续节点 Executor 任务隔离，空则用进程默认环境
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNodeCompletedRequest) Reset() {
	*x = ReportNodeCompletedRequest{}
	mi := &file_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNodeCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNodeCompletedRequest) ProtoMessage() {}

func (x *ReportNodeCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNodeCompletedRequest.ProtoReflect.Descriptor instead.
func (*ReportNodeCompletedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *ReportNodeCompletedRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *ReportNodeCompletedRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportNodeCompletedRequest) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ReportNodeCompletedRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// ReportNodeCompletedResponse 报告节点完成响应
type ReportNodeCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNodeCompletedResponse) Reset() {
	*x = ReportNodeCompletedResponse{}
	mi := &file_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNodeCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNodeCompletedResponse) ProtoMessage() {}

func (x *ReportNodeCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNodeCompletedResponse.ProtoReflect.Descriptor instead.
func (*ReportNodeCompletedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ReportNodeCompletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportNodeCompletedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RollbackToNodeRequest 回滚请求
type RollbackToNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int64                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`        // 工作流实例 ID（必填）
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // 目标节点 ID（必填）
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`                                         // 环境标识（如 dev/prod/test），用于 Executor 任务隔离，空则用进程默认环境
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackToNodeRequest) Reset() {
	*x = RollbackToNodeRequest{}
	mi := &file_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackToNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackToNodeRequest) ProtoMessage() {}

func (x *RollbackToNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackToNodeRequest.ProtoReflect.Descriptor instead.
func (*RollbackToNodeRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *RollbackToNodeRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *RollbackToNodeRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *RollbackToNodeRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// RollbackToNodeResponse 回滚响应
type RollbackToNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackToNodeResponse) Reset() {
	*x = RollbackToNodeResponse{}
	mi := &file_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackToNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackToNodeResponse) ProtoMessage() {}

func (x *RollbackToNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackToNodeResponse.ProtoReflect.Descriptor instead.
func (*RollbackToNodeResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *RollbackToNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackToNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetExecutionTrailRequest 获取执行轨迹请求
type GetExecutionTrailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int64                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 工作流实例 ID（必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionTrailRequest) Reset() {
	*x = GetExecutionTrailRequest{}
	mi := &file_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionTrailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionTrailRequest) ProtoMessage() {}

func (x *GetExecutionTrailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionTrailRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionTrailRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *GetExecutionTrailRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

// GetExecutionTrailResponse 获取执行轨迹响应
type GetExecutionTrailResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	InstanceId    int64                       `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`           // 工作流实例 ID
	Status        string                      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                      // 状态
	CurrentState  string                      `protobuf:"bytes,3,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`      // 当前状态 JSON
	ActiveNodeIds string                      `protobuf:"bytes,4,opt,name=active_node_ids,json=activeNodeIds,proto3" json:"active_node_ids,omitempty"` // 活动节点 ID 列表（逗号分隔）
	Checkpoints   []*ExecutionTrailCheckpoint `protobuf:"bytes,5,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`                            // 检查点列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionTrailResponse) Reset() {
	*x = GetExecutionTrailResponse{}
	mi := &file_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionTrailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionTrailResponse) ProtoMessage() {}

func (x *GetExecutionTrailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionTrailResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionTrailResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *GetExecutionTrailResponse) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *GetExecutionTrailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetExecutionTrailResponse) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *GetExecutionTrailResponse) GetActiveNodeIds() string {
	if x != nil {
		return x.ActiveNodeIds
	}
	return ""
}

func (x *GetExecutionTrailResponse) GetCheckpoints() []*ExecutionTrailCheckpoint {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

// ExecutionTrailCheckpoint 轨迹中的单步快照
type ExecutionTrailCheckpoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                           // 节点 ID
	NodeOutputJson string                 `protobuf:"bytes,2,opt,name=node_output_json,json=nodeOutputJson,proto3" json:"node_output_json,omitempty"` // 节点输出 JSON
	StateAfterJson string                 `protobuf:"bytes,3,opt,name=state_after_json,json=stateAfterJson,proto3" json:"state_after_json,omitempty"` // 节点执行后状态 JSON
	CreatedAt      string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                  // 创建时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionTrailCheckpoint) Reset() {
	*x = ExecutionTrailCheckpoint{}
	mi := &file_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTrailCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTrailCheckpoint) ProtoMessage() {}

func (x *ExecutionTrailCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTrailCheckpoint.ProtoReflect.Descriptor instead.
func (*ExecutionTrailCheckpoint) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *ExecutionTrailCheckpoint) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecutionTrailCheckpoint) GetNodeOutputJson() string {
	if x != nil {
		return x.NodeOutputJson
	}
	return ""
}

func (x *ExecutionTrailCheckpoint) GetStateAfterJson() string {
	if x != nil {
		return x.StateAfterJson
	}
	return ""
}

func (x *ExecutionTrailCheckpoint) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\x18xiaozhizhang.workflow.v1\"o\n" +
	"\x10CreateDefRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bdag_json\x18\x03 \x01(\tR\adagJson\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"*\n" +
	"\x11CreateDefResponse\x12\x15\n" +
	"\x06def_id\x18\x01 \x01(\x03R\x05defId\"o\n" +
	"\x14StartWorkflowRequest\x12\x19\n" +
	"\bdef_code\x18\x01 \x01(\tR\adefCode\x12*\n" +
	"\x11initial_data_json\x18\x02 \x01(\tR\x0finitialDataJson\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\"8\n" +
	"\x15StartWorkflowResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\"\x89\x01\n" +
	"\x1aReportNodeCompletedRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\voutput_json\x18\x03 \x01(\tR\n" +
	"outputJson\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\"Q\n" +
	"\x1bReportNodeCompletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\x15RollbackToNodeRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\"L\n" +
	"\x16RollbackToNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x18GetExecutionTrailRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\"\xf7\x01\n" +
	"\x19GetExecutionTrailResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_state\x18\x03 \x01(\tR\fcurrentState\x12&\n" +
	"\x0factive_node_ids\x18\x04 \x01(\tR\ractiveNodeIds\x12T\n" +
	"\vcheckpoints\x18\x05 \x03(\v22.xiaozhizhang.workflow.v1.ExecutionTrailCheckpointR\vcheckpoints\"\xa6\x01\n" +
	"\x18ExecutionTrailCheckpoint\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12(\n" +
	"\x10node_output_json\x18\x02 \x01(\tR\x0enodeOutputJson\x12(\n" +
	"\x10state_after_json\x18\x03 \x01(\tR\x0estateAfterJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt2\xe1\x04\n" +
	"\x0fWorkflowService\x12d\n" +
	"\tCreateDef\x12*.xiaozhizhang.workflow.v1.CreateDefRequest\x1a+.xiaozhizhang.workflow.v1.CreateDefResponse\x12p\n" +
	"\rStartWorkflow\x12..xiaozhizhang.workflow.v1.StartWorkflowRequest\x1a/.xiaozhizhang.workflow.v1.StartWorkflowResponse\x12\x82\x01\n" +
	"\x13ReportNodeCompleted\x124.xiaozhizhang.workflow.v1.ReportNodeCompletedRequest\x1a5.xiaozhizhang.workflow.v1.ReportNodeCompletedResponse\x12s\n" +
	"\x0eRollbackToNode\x12/.xiaozhizhang.workflow.v1.RollbackToNodeRequest\x1a0.xiaozhizhang.workflow.v1.RollbackToNodeResponse\x12|\n" +
	"\x11GetExecutionTrail\x122.xiaozhizhang.workflow.v1.GetExecutionTrailRequest\x1a3.xiaozhizhang.workflow.v1.GetExecutionTrailResponseB7Z5github.com/xsxdot/aio/system/workflow/api/proto;protob\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_workflow_proto_goTypes = []any{
	(*CreateDefRequest)(nil),            // 0: xiaozhizhang.workflow.v1.CreateDefRequest
	(*CreateDefResponse)(nil),           // 1: xiaozhizhang.workflow.v1.CreateDefResponse
	(*StartWorkflowRequest)(nil),        // 2: xiaozhizhang.workflow.v1.StartWorkflowRequest
	(*StartWorkflowResponse)(nil),       // 3: xiaozhizhang.workflow.v1.StartWorkflowResponse
	(*ReportNodeCompletedRequest)(nil),  // 4: xiaozhizhang.workflow.v1.ReportNodeCompletedRequest
	(*ReportNodeCompletedResponse)(nil), // 5: xiaozhizhang.workflow.v1.ReportNodeCompletedResponse
	(*RollbackToNodeRequest)(nil),       // 6: xiaozhizhang.workflow.v1.RollbackToNodeRequest
	(*RollbackToNodeResponse)(nil),      // 7: xiaozhizhang.workflow.v1.RollbackToNodeResponse
	(*GetExecutionTrailRequest)(nil),    // 8: xiaozhizhang.workflow.v1.GetExecutionTrailRequest
	(*GetExecutionTrailResponse)(nil),   // 9: xiaozhizhang.workflow.v1.GetExecutionTrailResponse
	(*ExecutionTrailCheckpoint)(nil),    // 10: xiaozhizhang.workflow.v1.ExecutionTrailCheckpoint
}
var file_workflow_proto_depIdxs = []int32{
	10, // 0: xiaozhizhang.workflow.v1.GetExecutionTrailResponse.checkpoints:type_name -> xiaozhizhang.workflow.v1.ExecutionTrailCheckpoint
	0,  // 1: xiaozhizhang.workflow.v1.WorkflowService.CreateDef:input_type -> xiaozhizhang.workflow.v1.CreateDefRequest
	2,  // 2: xiaozhizhang.workflow.v1.WorkflowService.StartWorkflow:input_type -> xiaozhizhang.workflow.v1.StartWorkflowRequest
	4,  // 3: xiaozhizhang.workflow.v1.WorkflowService.ReportNodeCompleted:input_type -> xiaozhizhang.workflow.v1.ReportNodeCompletedRequest
	6,  // 4: xiaozhizhang.workflow.v1.WorkflowService.RollbackToNode:input_type -> xiaozhizhang.workflow.v1.RollbackToNodeRequest
	8,  // 5: xiaozhizhang.workflow.v1.WorkflowService.GetExecutionTrail:input_type -> xiaozhizhang.workflow.v1.GetExecutionTrailRequest
	1,  // 6: xiaozhizhang.workflow.v1.WorkflowService.CreateDef:output_type -> xiaozhizhang.workflow.v1.CreateDefResponse
	3,  // 7: xiaozhizhang.workflow.v1.WorkflowService.StartWorkflow:output_type -> xiaozhizhang.workflow.v1.StartWorkflowResponse
	5,  // 8: xiaozhizhang.workflow.v1.WorkflowService.ReportNodeCompleted:output_type -> xiaozhizhang.workflow.v1.ReportNodeCompletedResponse
	7,  // 9: xiaozhizhang.workflow.v1.WorkflowService.RollbackToNode:output_type -> xiaozhizhang.workflow.v1.RollbackToNodeResponse
	9,  // 10: xiaozhizhang.workflow.v1.WorkflowService.GetExecutionTrail:output_type -> xiaozhizhang.workflow.v1.GetExecutionTrailResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
