// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.1
// source: executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobStatus 任务状态
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1 // 待执行
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2 // 执行中
	JobStatus_JOB_STATUS_SUCCEEDED   JobStatus = 3 // 成功
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4 // 失败（可重试）
	JobStatus_JOB_STATUS_CANCELED    JobStatus = 5 // 已取消
	JobStatus_JOB_STATUS_DEAD        JobStatus = 6 // 死信（超过最大重试次数）
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_SUCCEEDED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELED",
		6: "JOB_STATUS_DEAD",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_SUCCEEDED":   3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_CANCELED":    5,
		"JOB_STATUS_DEAD":        6,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_executor_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_executor_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

// SubscribeJobAvailableRequest 订阅任务可用请求
type SubscribeJobAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`                                          // 环境标识（必填）
	TargetService string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"` // 目标服务名（必填）
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`                                    // 方法名，空表示该 service 下任意方法
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeJobAvailableRequest) Reset() {
	*x = SubscribeJobAvailableRequest{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeJobAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeJobAvailableRequest) ProtoMessage() {}

func (x *SubscribeJobAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeJobAvailableRequest.ProtoReflect.Descriptor instead.
func (*SubscribeJobAvailableRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeJobAvailableRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *SubscribeJobAvailableRequest) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *SubscribeJobAvailableRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// JobAvailableHint 任务可用 hint（推送通知）
type JobAvailableHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetService string                 `protobuf:"bytes,1,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"` // 目标服务名
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                                    // 方法名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAvailableHint) Reset() {
	*x = JobAvailableHint{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAvailableHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAvailableHint) ProtoMessage() {}

func (x *JobAvailableHint) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAvailableHint.ProtoReflect.Descriptor instead.
func (*JobAvailableHint) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *JobAvailableHint) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *JobAvailableHint) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// SubmitJobRequest 提交任务请求
type SubmitJobRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Env              string                 `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`                                                       // 环境标识（必填，如 dev/prod/test）
	TargetService    string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`              // 目标服务名
	Method           string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`                                                 // 方法名
	ArgsJson         string                 `protobuf:"bytes,4,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`                             // 参数 JSON
	RunAt            int64                  `protobuf:"varint,5,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`                                     // 执行时间（Unix 时间戳秒），0表示立即执行
	MaxAttempts      int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`                   // 最大重试次数，默认3次
	DedupKey         string                 `protobuf:"bytes,7,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`                             // 幂等键（可选）
	Priority         int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`                                            // 优先级，数字越大优先级越高，默认0
	RetryBackoffType string                 `protobuf:"bytes,9,opt,name=retry_backoff_type,json=retryBackoffType,proto3" json:"retry_backoff_type,omitempty"`   // exponential | fixed，默认 exponential
	RetryIntervalSec int32                  `protobuf:"varint,10,opt,name=retry_interval_sec,json=retryIntervalSec,proto3" json:"retry_interval_sec,omitempty"` // 固定间隔秒数，仅 retry_backoff_type=fixed 时有效
	SequenceKey      string                 `protobuf:"bytes,11,opt,name=sequence_key,json=sequenceKey,proto3" json:"sequence_key,omitempty"`                   // 顺序键，同 key 的任务按顺序执行
	Source           string                 `protobuf:"bytes,12,opt,name=source,proto3" json:"source,omitempty"`                                                // 任务来源标识（如 workflow），非空表示需要触发完成回调
	CallbackData     string                 `protobuf:"bytes,13,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`                // 回调透传数据（JSON），由调用方自行约定格式
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitJobRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *SubmitJobRequest) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *SubmitJobRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SubmitJobRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *SubmitJobRequest) GetRunAt() int64 {
	if x != nil {
		return x.RunAt
	}
	return 0
}

func (x *SubmitJobRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *SubmitJobRequest) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *SubmitJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitJobRequest) GetRetryBackoffType() string {
	if x != nil {
		return x.RetryBackoffType
	}
	return ""
}

func (x *SubmitJobRequest) GetRetryIntervalSec() int32 {
	if x != nil {
		return x.RetryIntervalSec
	}
	return 0
}

func (x *SubmitJobRequest) GetSequenceKey() string {
	if x != nil {
		return x.SequenceKey
	}
	return ""
}

func (x *SubmitJobRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SubmitJobRequest) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

// SubmitJobResponse 提交任务响应
type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitJobResponse) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

// AcquireJobRequest 领取任务请求
type AcquireJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`                                           // 环境标识（必填，如 dev/prod/test）
	TargetService string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`  // 目标服务名（只能领取指定服务的任务）
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`           // 消费者ID（实例唯一标识）
	LeaseDuration int32                  `protobuf:"varint,4,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"` // 租约时长（秒），默认30秒
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`                                     // 可选：方法名过滤，空表示不过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireJobRequest) Reset() {
	*x = AcquireJobRequest{}
	mi := &file_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobRequest) ProtoMessage() {}

func (x *AcquireJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobRequest.ProtoReflect.Descriptor instead.
func (*AcquireJobRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{4}
}

func (x *AcquireJobRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *AcquireJobRequest) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *AcquireJobRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *AcquireJobRequest) GetLeaseDuration() int32 {
	if x != nil {
		return x.LeaseDuration
	}
	return 0
}

func (x *AcquireJobRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// AcquireJobResponse 领取任务响应
type AcquireJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                        // 任务ID，0表示没有可领取的任务
	AttemptNo     int32                  `protobuf:"varint,2,opt,name=attempt_no,json=attemptNo,proto3" json:"attempt_no,omitempty"`            // 当前尝试次数
	TargetService string                 `protobuf:"bytes,3,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"` // 目标服务名
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`                                    // 方法名
	ArgsJson      string                 `protobuf:"bytes,5,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`                // 参数 JSON
	LeaseUntil    int64                  `protobuf:"varint,6,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"`         // 租约到期时间（Unix 时间戳秒）
	Env           string                 `protobuf:"bytes,7,opt,name=env,proto3" json:"env,omitempty"`                                          // 环境标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireJobResponse) Reset() {
	*x = AcquireJobResponse{}
	mi := &file_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireJobResponse) ProtoMessage() {}

func (x *AcquireJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireJobResponse.ProtoReflect.Descriptor instead.
func (*AcquireJobResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{5}
}

func (x *AcquireJobResponse) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *AcquireJobResponse) GetAttemptNo() int32 {
	if x != nil {
		return x.AttemptNo
	}
	return 0
}

func (x *AcquireJobResponse) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *AcquireJobResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AcquireJobResponse) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *AcquireJobResponse) GetLeaseUntil() int64 {
	if x != nil {
		return x.LeaseUntil
	}
	return 0
}

func (x *AcquireJobResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// RenewLeaseRequest 续租请求
type RenewLeaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                            // 任务ID
	AttemptNo      int32                  `protobuf:"varint,2,opt,name=attempt_no,json=attemptNo,proto3" json:"attempt_no,omitempty"`                // 尝试次数（用于校验）
	ConsumerId     string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`              // 消费者ID
	ExtendDuration int32                  `protobuf:"varint,4,opt,name=extend_duration,json=extendDuration,proto3" json:"extend_duration,omitempty"` // 延长时长（秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenewLeaseRequest) Reset() {
	*x = RenewLeaseRequest{}
	mi := &file_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseRequest) ProtoMessage() {}

func (x *RenewLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{6}
}

func (x *RenewLeaseRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *RenewLeaseRequest) GetAttemptNo() int32 {
	if x != nil {
		return x.AttemptNo
	}
	return 0
}

func (x *RenewLeaseRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *RenewLeaseRequest) GetExtendDuration() int32 {
	if x != nil {
		return x.ExtendDuration
	}
	return 0
}

// RenewLeaseResponse 续租响应
type RenewLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                         // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // 消息
	LeaseUntil    int64                  `protobuf:"varint,3,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"` // 新的租约到期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseResponse) Reset() {
	*x = RenewLeaseResponse{}
	mi := &file_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseResponse) ProtoMessage() {}

func (x *RenewLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewLeaseResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{7}
}

func (x *RenewLeaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenewLeaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RenewLeaseResponse) GetLeaseUntil() int64 {
	if x != nil {
		return x.LeaseUntil
	}
	return 0
}

// AckJobRequest 确认任务请求
type AckJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                               // 任务ID
	AttemptNo      int32                  `protobuf:"varint,2,opt,name=attempt_no,json=attemptNo,proto3" json:"attempt_no,omitempty"`                   // 尝试次数（用于校验）
	ConsumerId     string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`                 // 消费者ID
	Status         JobStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=xiaozhizhang.executor.v1.JobStatus" json:"status,omitempty"`  // 执行结果状态（SUCCESS/FAILED）
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                             // 错误信息（失败时）
	ResultJson     string                 `protobuf:"bytes,6,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`                 // 结果 JSON（可选）
	RetryAfter     int32                  `protobuf:"varint,7,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`                // 重试延迟（秒），仅当status=FAILED时有效，0表示使用默认退避策略
	ErrorType      string                 `protobuf:"bytes,8,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`                    // 错误类型（如 TimeoutError）
	StopRetry      bool                   `protobuf:"varint,9,opt,name=stop_retry,json=stopRetry,proto3" json:"stop_retry,omitempty"`                   // true 表示立即标记为 dead，不再重试
	AddMaxAttempts int32                  `protobuf:"varint,10,opt,name=add_max_attempts,json=addMaxAttempts,proto3" json:"add_max_attempts,omitempty"` // 失败时增加的最大重试次数（如 +3 表示多 3 次机会）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AckJobRequest) Reset() {
	*x = AckJobRequest{}
	mi := &file_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckJobRequest) ProtoMessage() {}

func (x *AckJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckJobRequest.ProtoReflect.Descriptor instead.
func (*AckJobRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{8}
}

func (x *AckJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *AckJobRequest) GetAttemptNo() int32 {
	if x != nil {
		return x.AttemptNo
	}
	return 0
}

func (x *AckJobRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *AckJobRequest) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *AckJobRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AckJobRequest) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *AckJobRequest) GetRetryAfter() int32 {
	if x != nil {
		return x.RetryAfter
	}
	return 0
}

func (x *AckJobRequest) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *AckJobRequest) GetStopRetry() bool {
	if x != nil {
		return x.StopRetry
	}
	return false
}

func (x *AckJobRequest) GetAddMaxAttempts() int32 {
	if x != nil {
		return x.AddMaxAttempts
	}
	return 0
}

// AckJobResponse 确认任务响应
type AckJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckJobResponse) Reset() {
	*x = AckJobResponse{}
	mi := &file_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckJobResponse) ProtoMessage() {}

func (x *AckJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckJobResponse.ProtoReflect.Descriptor instead.
func (*AckJobResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{9}
}

func (x *AckJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetJobRequest 获取任务请求
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10}
}

func (x *GetJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

// JobResponse 任务详情响应
type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                 // 任务ID
	TargetService string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`       // 目标服务名
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`                                          // 方法名
	ArgsJson      string                 `protobuf:"bytes,4,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`                      // 参数 JSON
	Status        JobStatus              `protobuf:"varint,5,opt,name=status,proto3,enum=xiaozhizhang.executor.v1.JobStatus" json:"status,omitempty"` // 状态
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`                                     // 优先级
	NextRunAt     int64                  `protobuf:"varint,7,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`                // 下次执行时间
	MaxAttempts   int32                  `protobuf:"varint,8,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`            // 最大重试次数
	Attempts      int32                  `protobuf:"varint,9,opt,name=attempts,proto3" json:"attempts,omitempty"`                                     // 已尝试次数
	LeaseOwner    string                 `protobuf:"bytes,10,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`               // 租约持有者
	LeaseUntil    int64                  `protobuf:"varint,11,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"`              // 租约到期时间
	DedupKey      string                 `protobuf:"bytes,12,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`                     // 幂等键
	LastError     string                 `protobuf:"bytes,13,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`                  // 最后错误
	ResultJson    string                 `protobuf:"bytes,14,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`               // 结果 JSON
	CreatedAt     int64                  `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                 // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                 // 更新时间
	Env           string                 `protobuf:"bytes,17,opt,name=env,proto3" json:"env,omitempty"`                                               // 环境标识
	SequenceKey   string                 `protobuf:"bytes,18,opt,name=sequence_key,json=sequenceKey,proto3" json:"sequence_key,omitempty"`            // 顺序键
	LastErrorType string                 `protobuf:"bytes,19,opt,name=last_error_type,json=lastErrorType,proto3" json:"last_error_type,omitempty"`    // 最后错误类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{11}
}

func (x *JobResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobResponse) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *JobResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *JobResponse) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

func (x *JobResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *JobResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JobResponse) GetNextRunAt() int64 {
	if x != nil {
		return x.NextRunAt
	}
	return 0
}

func (x *JobResponse) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *JobResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *JobResponse) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *JobResponse) GetLeaseUntil() int64 {
	if x != nil {
		return x.LeaseUntil
	}
	return 0
}

func (x *JobResponse) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *JobResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *JobResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *JobResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *JobResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *JobResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *JobResponse) GetSequenceKey() string {
	if x != nil {
		return x.SequenceKey
	}
	return ""
}

func (x *JobResponse) GetLastErrorType() string {
	if x != nil {
		return x.LastErrorType
	}
	return ""
}

// ListJobsRequest 列出任务请求
type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`                                                // 环境标识（必填，如 dev/prod/test）
	TargetService string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`       // 目标服务名（可选）
	Status        JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=xiaozhizhang.executor.v1.JobStatus" json:"status,omitempty"` // 状态过滤（可选）
	PageNum       int32                  `protobuf:"varint,4,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`                        // 页码，从1开始
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                     // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{12}
}

func (x *ListJobsRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *ListJobsRequest) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *ListJobsRequest) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ListJobsRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListJobsResponse 列出任务响应
type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobResponse         `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`    // 任务列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{13}
}

func (x *ListJobsResponse) GetJobs() []*JobResponse {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// CancelJobRequest 取消任务请求
type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{14}
}

func (x *CancelJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

// CancelJobResponse 取消任务响应
type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_executor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{15}
}

func (x *CancelJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RequeueJobRequest 重新入队请求
type RequeueJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // 任务ID
	RunAt         int64                  `protobuf:"varint,2,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"` // 执行时间（Unix 时间戳秒），0表示立即执行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequeueJobRequest) Reset() {
	*x = RequeueJobRequest{}
	mi := &file_executor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequeueJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequeueJobRequest) ProtoMessage() {}

func (x *RequeueJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequeueJobRequest.ProtoReflect.Descriptor instead.
func (*RequeueJobRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{16}
}

func (x *RequeueJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *RequeueJobRequest) GetRunAt() int64 {
	if x != nil {
		return x.RunAt
	}
	return 0
}

// RequeueJobResponse 重新入队响应
type RequeueJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequeueJobResponse) Reset() {
	*x = RequeueJobResponse{}
	mi := &file_executor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequeueJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequeueJobResponse) ProtoMessage() {}

func (x *RequeueJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequeueJobResponse.ProtoReflect.Descriptor instead.
func (*RequeueJobResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{17}
}

func (x *RequeueJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequeueJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateJobArgsRequest 更新任务参数请求
type UpdateJobArgsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`         // 任务ID
	ArgsJson      string                 `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"` // 参数 JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobArgsRequest) Reset() {
	*x = UpdateJobArgsRequest{}
	mi := &file_executor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobArgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobArgsRequest) ProtoMessage() {}

func (x *UpdateJobArgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobArgsRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobArgsRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateJobArgsRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *UpdateJobArgsRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

// UpdateJobArgsResponse 更新任务参数响应
type UpdateJobArgsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobArgsResponse) Reset() {
	*x = UpdateJobArgsResponse{}
	mi := &file_executor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobArgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobArgsResponse) ProtoMessage() {}

func (x *UpdateJobArgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobArgsResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobArgsResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateJobArgsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateJobArgsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_executor_proto protoreflect.FileDescriptor

const file_executor_proto_rawDesc = "" +
	"\n" +
	"\x0eexecutor.proto\x12\x18xiaozhizhang.executor.v1\"o\n" +
	"\x1cSubscribeJobAvailableRequest\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03env\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"Q\n" +
	"\x10JobAvailableHint\x12%\n" +
	"\x0etarget_service\x18\x01 \x01(\tR\rtargetService\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"\xaf\x03\n" +
	"\x10SubmitJobRequest\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03env\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1b\n" +
	"\targs_json\x18\x04 \x01(\tR\bargsJson\x12\x15\n" +
	"\x06run_at\x18\x05 \x01(\x03R\x05runAt\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12\x1b\n" +
	"\tdedup_key\x18\a \x01(\tR\bdedupKey\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12,\n" +
	"\x12retry_backoff_type\x18\t \x01(\tR\x10retryBackoffType\x12,\n" +
	"\x12retry_interval_sec\x18\n" +
	" \x01(\x05R\x10retryIntervalSec\x12!\n" +
	"\fsequence_key\x18\v \x01(\tR\vsequenceKey\x12\x16\n" +
	"\x06source\x18\f \x01(\tR\x06source\x12#\n" +
	"\rcallback_data\x18\r \x01(\tR\fcallbackData\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"\xac\x01\n" +
	"\x11AcquireJobRequest\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03env\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\x12%\n" +
	"\x0elease_duration\x18\x04 \x01(\x05R\rleaseDuration\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\"\xd9\x01\n" +
	"\x12AcquireJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_no\x18\x02 \x01(\x05R\tattemptNo\x12%\n" +
	"\x0etarget_service\x18\x03 \x01(\tR\rtargetService\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1b\n" +
	"\targs_json\x18\x05 \x01(\tR\bargsJson\x12\x1f\n" +
	"\vlease_until\x18\x06 \x01(\x03R\n" +
	"leaseUntil\x12\x10\n" +
	"\x03env\x18\a \x01(\tR\x03env\"\x93\x01\n" +
	"\x11RenewLeaseRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_no\x18\x02 \x01(\x05R\tattemptNo\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\x12'\n" +
	"\x0fextend_duration\x18\x04 \x01(\x05R\x0eextendDuration\"i\n" +
	"\x12RenewLeaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vlease_until\x18\x03 \x01(\x03R\n" +
	"leaseUntil\"\xe3\x02\n" +
	"\rAckJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_no\x18\x02 \x01(\x05R\tattemptNo\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.xiaozhizhang.executor.v1.JobStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vresult_json\x18\x06 \x01(\tR\n" +
	"resultJson\x12\x1f\n" +
	"\vretry_after\x18\a \x01(\x05R\n" +
	"retryAfter\x12\x1d\n" +
	"\n" +
	"error_type\x18\b \x01(\tR\terrorType\x12\x1d\n" +
	"\n" +
	"stop_retry\x18\t \x01(\bR\tstopRetry\x12(\n" +
	"\x10add_max_attempts\x18\n" +
	" \x01(\x05R\x0eaddMaxAttempts\"D\n" +
	"\x0eAckJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"\xeb\x04\n" +
	"\vJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1b\n" +
	"\targs_json\x18\x04 \x01(\tR\bargsJson\x12;\n" +
	"\x06status\x18\x05 \x01(\x0e2#.xiaozhizhang.executor.v1.JobStatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1e\n" +
	"\vnext_run_at\x18\a \x01(\x03R\tnextRunAt\x12!\n" +
	"\fmax_attempts\x18\b \x01(\x05R\vmaxAttempts\x12\x1a\n" +
	"\battempts\x18\t \x01(\x05R\battempts\x12\x1f\n" +
	"\vlease_owner\x18\n" +
	" \x01(\tR\n" +
	"leaseOwner\x12\x1f\n" +
	"\vlease_until\x18\v \x01(\x03R\n" +
	"leaseUntil\x12\x1b\n" +
	"\tdedup_key\x18\f \x01(\tR\bdedupKey\x12\x1d\n" +
	"\n" +
	"last_error\x18\r \x01(\tR\tlastError\x12\x1f\n" +
	"\vresult_json\x18\x0e \x01(\tR\n" +
	"resultJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\x03R\tupdatedAt\x12\x10\n" +
	"\x03env\x18\x11 \x01(\tR\x03env\x12!\n" +
	"\fsequence_key\x18\x12 \x01(\tR\vsequenceKey\x12&\n" +
	"\x0flast_error_type\x18\x13 \x01(\tR\rlastErrorType\"\xbf\x01\n" +
	"\x0fListJobsRequest\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03env\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.xiaozhizhang.executor.v1.JobStatusR\x06status\x12\x19\n" +
	"\bpage_num\x18\x04 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"c\n" +
	"\x10ListJobsResponse\x129\n" +
	"\x04jobs\x18\x01 \x03(\v2%.xiaozhizhang.executor.v1.JobResponseR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"G\n" +
	"\x11CancelJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x11RequeueJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x15\n" +
	"\x06run_at\x18\x02 \x01(\x03R\x05runAt\"H\n" +
	"\x12RequeueJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x14UpdateJobArgsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x1b\n" +
	"\targs_json\x18\x02 \x01(\tR\bargsJson\"K\n" +
	"\x15UpdateJobArgsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xb6\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x17\n" +
	"\x13JOB_STATUS_CANCELED\x10\x05\x12\x13\n" +
	"\x0fJOB_STATUS_DEAD\x10\x062\xa3\b\n" +
	"\x0fExecutorService\x12d\n" +
	"\tSubmitJob\x12*.xiaozhizhang.executor.v1.SubmitJobRequest\x1a+.xiaozhizhang.executor.v1.SubmitJobResponse\x12g\n" +
	"\n" +
	"AcquireJob\x12+.xiaozhizhang.executor.v1.AcquireJobRequest\x1a,.xiaozhizhang.executor.v1.AcquireJobResponse\x12g\n" +
	"\n" +
	"RenewLease\x12+.xiaozhizhang.executor.v1.RenewLeaseRequest\x1a,.xiaozhizhang.executor.v1.RenewLeaseResponse\x12[\n" +
	"\x06AckJob\x12'.xiaozhizhang.executor.v1.AckJobRequest\x1a(.xiaozhizhang.executor.v1.AckJobResponse\x12X\n" +
	"\x06GetJob\x12'.xiaozhizhang.executor.v1.GetJobRequest\x1a%.xiaozhizhang.executor.v1.JobResponse\x12a\n" +
	"\bListJobs\x12).xiaozhizhang.executor.v1.ListJobsRequest\x1a*.xiaozhizhang.executor.v1.ListJobsResponse\x12d\n" +
	"\tCancelJob\x12*.xiaozhizhang.executor.v1.CancelJobRequest\x1a+.xiaozhizhang.executor.v1.CancelJobResponse\x12g\n" +
	"\n" +
	"RequeueJob\x12+.xiaozhizhang.executor.v1.RequeueJobRequest\x1a,.xiaozhizhang.executor.v1.RequeueJobResponse\x12p\n" +
	"\rUpdateJobArgs\x12..xiaozhizhang.executor.v1.UpdateJobArgsRequest\x1a/.xiaozhizhang.executor.v1.UpdateJobArgsResponse\x12}\n" +
	"\x15SubscribeJobAvailable\x126.xiaozhizhang.executor.v1.SubscribeJobAvailableRequest\x1a*.xiaozhizhang.executor.v1.JobAvailableHint0\x01B.Z,xiaozhizhang/system/executor/api/proto;protob\x06proto3"

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData []byte
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)))
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_executor_proto_goTypes = []any{
	(JobStatus)(0),                       // 0: xiaozhizhang.executor.v1.JobStatus
	(*SubscribeJobAvailableRequest)(nil), // 1: xiaozhizhang.executor.v1.SubscribeJobAvailableRequest
	(*JobAvailableHint)(nil),             // 2: xiaozhizhang.executor.v1.JobAvailableHint
	(*SubmitJobRequest)(nil),             // 3: xiaozhizhang.executor.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),            // 4: xiaozhizhang.executor.v1.SubmitJobResponse
	(*AcquireJobRequest)(nil),            // 5: xiaozhizhang.executor.v1.AcquireJobRequest
	(*AcquireJobResponse)(nil),           // 6: xiaozhizhang.executor.v1.AcquireJobResponse
	(*RenewLeaseRequest)(nil),            // 7: xiaozhizhang.executor.v1.RenewLeaseRequest
	(*RenewLeaseResponse)(nil),           // 8: xiaozhizhang.executor.v1.RenewLeaseResponse
	(*AckJobRequest)(nil),                // 9: xiaozhizhang.executor.v1.AckJobRequest
	(*AckJobResponse)(nil),               // 10: xiaozhizhang.executor.v1.AckJobResponse
	(*GetJobRequest)(nil),                // 11: xiaozhizhang.executor.v1.GetJobRequest
	(*JobResponse)(nil),                  // 12: xiaozhizhang.executor.v1.JobResponse
	(*ListJobsRequest)(nil),              // 13: xiaozhizhang.executor.v1.ListJobsRequest
	(*ListJobsResponse)(nil),             // 14: xiaozhizhang.executor.v1.ListJobsResponse
	(*CancelJobRequest)(nil),             // 15: xiaozhizhang.executor.v1.CancelJobRequest
	(*CancelJobResponse)(nil),            // 16: xiaozhizhang.executor.v1.CancelJobResponse
	(*RequeueJobRequest)(nil),            // 17: xiaozhizhang.executor.v1.RequeueJobRequest
	(*RequeueJobResponse)(nil),           // 18: xiaozhizhang.executor.v1.RequeueJobResponse
	(*UpdateJobArgsRequest)(nil),         // 19: xiaozhizhang.executor.v1.UpdateJobArgsRequest
	(*UpdateJobArgsResponse)(nil),        // 20: xiaozhizhang.executor.v1.UpdateJobArgsResponse
}
var file_executor_proto_depIdxs = []int32{
	0,  // 0: xiaozhizhang.executor.v1.AckJobRequest.status:type_name -> xiaozhizhang.executor.v1.JobStatus
	0,  // 1: xiaozhizhang.executor.v1.JobResponse.status:type_name -> xiaozhizhang.executor.v1.JobStatus
	0,  // 2: xiaozhizhang.executor.v1.ListJobsRequest.status:type_name -> xiaozhizhang.executor.v1.JobStatus
	12, // 3: xiaozhizhang.executor.v1.ListJobsResponse.jobs:type_name -> xiaozhizhang.executor.v1.JobResponse
	3,  // 4: xiaozhizhang.executor.v1.ExecutorService.SubmitJob:input_type -> xiaozhizhang.executor.v1.SubmitJobRequest
	5,  // 5: xiaozhizhang.executor.v1.ExecutorService.AcquireJob:input_type -> xiaozhizhang.executor.v1.AcquireJobRequest
	7,  // 6: xiaozhizhang.executor.v1.ExecutorService.RenewLease:input_type -> xiaozhizhang.executor.v1.RenewLeaseRequest
	9,  // 7: xiaozhizhang.executor.v1.ExecutorService.AckJob:input_type -> xiaozhizhang.executor.v1.AckJobRequest
	11, // 8: xiaozhizhang.executor.v1.ExecutorService.GetJob:input_type -> xiaozhizhang.executor.v1.GetJobRequest
	13, // 9: xiaozhizhang.executor.v1.ExecutorService.ListJobs:input_type -> xiaozhizhang.executor.v1.ListJobsRequest
	15, // 10: xiaozhizhang.executor.v1.ExecutorService.CancelJob:input_type -> xiaozhizhang.executor.v1.CancelJobRequest
	17, // 11: xiaozhizhang.executor.v1.ExecutorService.RequeueJob:input_type -> xiaozhizhang.executor.v1.RequeueJobRequest
	19, // 12: xiaozhizhang.executor.v1.ExecutorService.UpdateJobArgs:input_type -> xiaozhizhang.executor.v1.UpdateJobArgsRequest
	1,  // 13: xiaozhizhang.executor.v1.ExecutorService.SubscribeJobAvailable:input_type -> xiaozhizhang.executor.v1.SubscribeJobAvailableRequest
	4,  // 14: xiaozhizhang.executor.v1.ExecutorService.SubmitJob:output_type -> xiaozhizhang.executor.v1.SubmitJobResponse
	6,  // 15: xiaozhizhang.executor.v1.ExecutorService.AcquireJob:output_type -> xiaozhizhang.executor.v1.AcquireJobResponse
	8,  // 16: xiaozhizhang.executor.v1.ExecutorService.RenewLease:output_type -> xiaozhizhang.executor.v1.RenewLeaseResponse
	10, // 17: xiaozhizhang.executor.v1.ExecutorService.AckJob:output_type -> xiaozhizhang.executor.v1.AckJobResponse
	12, // 18: xiaozhizhang.executor.v1.ExecutorService.GetJob:output_type -> xiaozhizhang.executor.v1.JobResponse
	14, // 19: xiaozhizhang.executor.v1.ExecutorService.ListJobs:output_type -> xiaozhizhang.executor.v1.ListJobsResponse
	16, // 20: xiaozhizhang.executor.v1.ExecutorService.CancelJob:output_type -> xiaozhizhang.executor.v1.CancelJobResponse
	18, // 21: xiaozhizhang.executor.v1.ExecutorService.RequeueJob:output_type -> xiaozhizhang.executor.v1.RequeueJobResponse
	20, // 22: xiaozhizhang.executor.v1.ExecutorService.UpdateJobArgs:output_type -> xiaozhizhang.executor.v1.UpdateJobArgsResponse
	2,  // 23: xiaozhizhang.executor.v1.ExecutorService.SubscribeJobAvailable:output_type -> xiaozhizhang.executor.v1.JobAvailableHint
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		EnumInfos:         file_executor_proto_enumTypes,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
