// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.1
// source: server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServerService_ReportServerStatus_FullMethodName = "/xiaozhizhang.server.v1.ServerService/ReportServerStatus"
	ServerService_GetAllServerStatus_FullMethodName = "/xiaozhizhang.server.v1.ServerService/GetAllServerStatus"
	ServerService_GetServerStatus_FullMethodName    = "/xiaozhizhang.server.v1.ServerService/GetServerStatus"
)

// ServerServiceClient is the client API for ServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServerService 服务器管理服务
type ServerServiceClient interface {
	// 上报服务器状态（供 agent/脚本调用）
	ReportServerStatus(ctx context.Context, in *ReportServerStatusRequest, opts ...grpc.CallOption) (*ReportServerStatusResponse, error)
	// 获取所有服务器状态（主页聚合查询）
	GetAllServerStatus(ctx context.Context, in *GetAllServerStatusRequest, opts ...grpc.CallOption) (*GetAllServerStatusResponse, error)
	// 获取单个服务器状态
	GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*ServerStatusInfo, error)
}

type serverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServerServiceClient(cc grpc.ClientConnInterface) ServerServiceClient {
	return &serverServiceClient{cc}
}

func (c *serverServiceClient) ReportServerStatus(ctx context.Context, in *ReportServerStatusRequest, opts ...grpc.CallOption) (*ReportServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportServerStatusResponse)
	err := c.cc.Invoke(ctx, ServerService_ReportServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) GetAllServerStatus(ctx context.Context, in *GetAllServerStatusRequest, opts ...grpc.CallOption) (*GetAllServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllServerStatusResponse)
	err := c.cc.Invoke(ctx, ServerService_GetAllServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*ServerStatusInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerStatusInfo)
	err := c.cc.Invoke(ctx, ServerService_GetServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServiceServer is the server API for ServerService service.
// All implementations must embed UnimplementedServerServiceServer
// for forward compatibility.
//
// ServerService 服务器管理服务
type ServerServiceServer interface {
	// 上报服务器状态（供 agent/脚本调用）
	ReportServerStatus(context.Context, *ReportServerStatusRequest) (*ReportServerStatusResponse, error)
	// 获取所有服务器状态（主页聚合查询）
	GetAllServerStatus(context.Context, *GetAllServerStatusRequest) (*GetAllServerStatusResponse, error)
	// 获取单个服务器状态
	GetServerStatus(context.Context, *GetServerStatusRequest) (*ServerStatusInfo, error)
	mustEmbedUnimplementedServerServiceServer()
}

// UnimplementedServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerServiceServer struct{}

func (UnimplementedServerServiceServer) ReportServerStatus(context.Context, *ReportServerStatusRequest) (*ReportServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportServerStatus not implemented")
}
func (UnimplementedServerServiceServer) GetAllServerStatus(context.Context, *GetAllServerStatusRequest) (*GetAllServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllServerStatus not implemented")
}
func (UnimplementedServerServiceServer) GetServerStatus(context.Context, *GetServerStatusRequest) (*ServerStatusInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedServerServiceServer) mustEmbedUnimplementedServerServiceServer() {}
func (UnimplementedServerServiceServer) testEmbeddedByValue()                       {}

// UnsafeServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServiceServer will
// result in compilation errors.
type UnsafeServerServiceServer interface {
	mustEmbedUnimplementedServerServiceServer()
}

func RegisterServerServiceServer(s grpc.ServiceRegistrar, srv ServerServiceServer) {
	// If the following call pancis, it indicates UnimplementedServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerService_ServiceDesc, srv)
}

func _ServerService_ReportServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).ReportServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerService_ReportServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).ReportServerStatus(ctx, req.(*ReportServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_GetAllServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).GetAllServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerService_GetAllServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).GetAllServerStatus(ctx, req.(*GetAllServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_GetServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).GetServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerService_GetServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).GetServerStatus(ctx, req.(*GetServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerService_ServiceDesc is the grpc.ServiceDesc for ServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xiaozhizhang.server.v1.ServerService",
	HandlerType: (*ServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportServerStatus",
			Handler:    _ServerService_ReportServerStatus_Handler,
		},
		{
			MethodName: "GetAllServerStatus",
			Handler:    _ServerService_GetAllServerStatus_Handler,
		},
		{
			MethodName: "GetServerStatus",
			Handler:    _ServerService_GetServerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
